fileOpsType=local
buildMapClientType=json
buildMapPath=/Users/bomitalievelino/Documents/Workspace/isp-ibm-mauden/repo/pulizia-cassaforte/full-fat-source/src/test/sh/local/resources/buildmap.json
uxBasedir=/var/folders/06/3mcb33yn2mj974q42s03pyk00000gn/T//run-puliziacassaforte.39306
rulesPath=/Users/bomitalievelino/Documents/Workspace/isp-ibm-mauden/repo/pulizia-cassaforte/full-fat-source/src/test/sh/local/resources/rulest2.csv
stageMapPath=/Users/bomitalievelino/Documents/Workspace/isp-ibm-mauden/repo/pulizia-cassaforte/full-fat-source/src/test/sh/local/resources/stagemap.csv
