fileOpsType=local
buildMapClientType=json
buildMapPath=/Users/bomitalievelino/Documents/Workspace/isp-ibm-mauden/repo/pulizia-cassaforte-dev/uss/src/test/sh/resources/buildmap.json
uxBasedir=/var/folders/06/3mcb33yn2mj974q42s03pyk00000gn/T//run-puliziacassaforte.69292
rulesPath=/Users/bomitalievelino/Documents/Workspace/isp-ibm-mauden/repo/pulizia-cassaforte-dev/uss/src/test/sh/resources/rules.csv
stageMapPath=/Users/bomitalievelino/Documents/Workspace/isp-ibm-mauden/repo/pulizia-cassaforte-dev/uss/src/test/sh/resources/stagemap.csv
