// ============================================================
// FAT SOURCE — auto-generated by merge_groovy.py
// Sources merged: 22 files from '/Users/bomitalievelino/Documents/Workspace/isp-ibm-mauden/repo/pulizia-cassaforte-main/fat-source/build/temp-sources'
// ============================================================

import com.ibm.dbb.build.BuildException
import com.ibm.dbb.metadata.BuildGroup
import com.ibm.dbb.metadata.BuildMap
import com.ibm.dbb.metadata.MetadataStore
import com.ibm.dbb.metadata.MetadataStoreFactory
import com.ibm.dbb.task.BuildContext
import com.ibm.jzos.PdsDirectory
import com.ibm.jzos.PdsDirectory.MemberInfo
import com.ibm.jzos.ZFile
import com.ibm.jzos.ZFileException
import groovy.json.JsonSlurper
import groovy.util.logging.Slf4j
import java.nio.file.*
import java.util.concurrent.atomic.AtomicInteger
import java.util.regex.Pattern

// --- BuildMapClient.groovy ---
/**
 * Trait (interface) for querying the DBB build map to resolve generated output objects.
 *
 * <p>In the cassaforte deletion flow, when a {@link DeletionRule} has {@code useBuildMap = true},
 * the generated member name (which may differ from the source name) must be looked up before
 * the PDS entry can be deleted.  This trait decouples that lookup from the deletion logic.
 *
 * <p>Three implementations:
 * <ul>
 *   <li>{@link JsonBuildMapClient}  — reads a pre-captured JSON fixture; no IBM deps; used in unit tests and local dev.</li>
 *   <li>{@code Db2BuildMapClient}   — queries the live DBB DB2 metadata store on USS; lazy DB2 connection.</li>
 *   <li>{@code DbbBuildMapClient}   — pulls {@code BUILD_GROUP} from a running DBB {@code BuildContext}; no extra DB2 connection.</li>
 * </ul>
 *
 * @see DeletionRule#useBuildMap
 * @see DeleteCassaforteLogic
 */
@Slf4j
abstract class BuildMapClient {
    String buildGroupName
    abstract List<Map<String, String>> getGeneratedObjects(String sourcePath)
}

// --- Db2BuildMapClient.groovy ---
// Mainframe-only. Must be compiled and run with groovyz on z/OS USS.
// After upload to USS: chtag -tc IBM-1047 Db2BuildMapClient.groovy

/**
 * DB2-backed implementation of {@link BuildMapClient} that queries the live DBB metadata store
 * to resolve generated output objects for a given source file.
 *
 * <p>Two acquisition paths for the {@link BuildGroup}:
 * <ul>
 *   <li><b>Config-driven</b> ({@code PuliziaCassaforte.groovy} standalone): use the primary
 *       constructor with {@link PuliziaCassaforteConfig} — the DB2 connection is deferred until
 *       the first call to {@link #getGeneratedObjects}, so no connection is made when no rule
 *       uses {@code useBuildMap = true}.</li>
 *   <li><b>Direct injection</b> (tests): use {@code Db2BuildMapClient(BuildGroup)} to inject
 *       a mock or pre-fetched group without touching the DB2 stack.</li>
 * </ul>
 *
 * <p>Compiled against DBB metadata stubs (compileOnly) so it builds locally without IBM jars.
 * At runtime on z/OS USS the real DBB jars must be on the classpath.
 *
 * @see BuildMapClient
 * @see JsonBuildMapClient
 */
@Slf4j
class Db2BuildMapClient extends BuildMapClient {

    private BuildGroup buildGroup

    private final String userId
    private final String pwFilePath
    private final String db2ConfigPath

    /**
     * Primary constructor: deferred DB2 connection.
     * Stores credentials from {@code cfg}; no file reading or DB2 connection is made until
     * {@link #getGeneratedObjects} is first called.
     */
    Db2BuildMapClient(String buildGroupName, PuliziaCassaforteConfig cfg) {
        this.buildGroupName = buildGroupName
        this.buildGroup     = null
        this.userId         = cfg.userId
        this.pwFilePath     = cfg.pwFilePath
        this.db2ConfigPath  = cfg.db2ConfigPath
        log.debug("Db2BuildMapClient configured for group '{}' (deferred connection)", buildGroupName)
    }

    /**
     * Injection constructor for tests and task-context pass-through.
     * Accepts an already-fetched {@link BuildGroup} — no DB2 connection made.
     *
     * @param buildGroup  DBB {@link BuildGroup} for the current build; in a task context
     *                    obtain via {@code context.get('BUILD_GROUP') as BuildGroup}.
     */
    Db2BuildMapClient(BuildGroup buildGroup) {
        this.buildGroup     = buildGroup
        this.buildGroupName = buildGroup?.getName()
        this.userId         = null
        this.pwFilePath     = null
        this.db2ConfigPath  = null
        log.debug("Db2BuildMapClient initialized for group '{}'", buildGroupName)
    }

    private BuildGroup resolveBuildGroup() {
        if (buildGroup == null) {
            def db2Props = loadDb2Props(db2ConfigPath)
            log.info("Connecting to metadata store: group='{}' user='{}' url='{}'",
                     buildGroupName, userId, db2Props?.getProperty('url'))
            MetadataStore store = MetadataStoreFactory.createDb2MetadataStore(
                userId, new File(pwFilePath), db2Props)
            buildGroup = store.getBuildGroup(buildGroupName)
            if (!buildGroup) {
                log.error("Build group '{}' not found in metadata store", buildGroupName)
                throw new IllegalStateException("Build group '${buildGroupName}' not found in metadata store")
            }
        }
        return buildGroup
    }

    /**
     * Returns the output PDS members produced from {@code sourcePath} in the build map
     * stored under that path within the resolved {@link BuildGroup}.
     *
     * @param sourcePath  Repository-relative source file path (the build map label).
     * @return            List of {@code {library, member}} maps; empty if no record is found.
     */
    List<Map<String, String>> getGeneratedObjects(String sourcePath) {
        try {
            BuildMap bm = resolveBuildGroup().getBuildMap(sourcePath)
            if (!bm) {
                log.debug("getGeneratedObjects: no build map entry for '{}'", sourcePath)
                return []
            }

            def result = bm.getOutputs()
                .findAll { it.getDataset() && it.getMember() }
                .collect { [library: it.getDataset(), member: it.getMember()] }
            log.debug("getGeneratedObjects: '{}' -> {} object(s)", sourcePath, result.size())
            log.debug("Dump build map\n{}", bm.toString())
            return result

        } catch (BuildException e) {
            log.warn("getGeneratedObjects: BuildException for '{}': {}", sourcePath, e.message)
            return []
        }
    }

    private static Properties loadDb2Props(String db2ConfigPath) {
        def props = new Properties()
        new File(db2ConfigPath).withInputStream { stream -> props.load(stream) }
        return props
    }
}

// --- DbbBuildMapClient.groovy ---
// Mainframe-only. Must be compiled and run with groovyz in a DBB task or groovy step.
// After upload to USS: chtag -tc IBM-1047 DbbBuildMapClient.groovy

/**
 * DBB-task-context implementation of {@link BuildMapClient}.
 *
 * <p>Reuses the {@link BuildGroup} already resolved by the {@code MetadataInit} built-in task
 * and available in the running {@link BuildContext} as {@code BUILD_GROUP}.  No DB2 connection
 * is made by this client — the group is simply pulled from the context on the first call to
 * {@link #getGeneratedObjects}.
 *
 * <p>Usage from a DBB task script:
 * <pre>
 *   def client = new DbbBuildMapClient(buildGroupName, cfg)
 *   client.setContext(context)   // inject the running BuildContext
 * </pre>
 *
 * <p>Compiled against DBB metadata stubs (compileOnly) so it builds locally without IBM jars.
 * At runtime on z/OS USS the real DBB jars must be on the classpath.
 *
 * @see BuildMapClient
 * @see Db2BuildMapClient
 */
@Slf4j
class DbbBuildMapClient extends BuildMapClient {

    private BuildGroup  buildGroup
    private BuildContext context

    /**
     * Primary constructor: {@link BuildContext} must be injected via {@link #setContext} before
     * the first {@link #getGeneratedObjects} call.
     */
    DbbBuildMapClient(String buildGroupName, PuliziaCassaforteConfig cfg) {
        this.buildGroupName = buildGroupName
        this.buildGroup     = null
        this.context        = null
        log.debug("DbbBuildMapClient configured for group '{}' (context not yet injected)", buildGroupName)
    }

    /**
     * Injection constructor for task scripts that already hold the {@link BuildContext}.
     *
     * @param buildGroupName  DBB build group name (used for logging and validation).
     * @param context         Running DBB {@link BuildContext}; must contain {@code BUILD_GROUP}.
     */
    DbbBuildMapClient(String buildGroupName, BuildContext context) {
        this.buildGroupName = buildGroupName
        this.buildGroup     = null
        this.context        = context
        log.debug("DbbBuildMapClient configured for group '{}' with injected context", buildGroupName)
    }

    /** Allows late injection of the {@link BuildContext} after construction. */
    void setContext(BuildContext context) {
        this.context = context
    }

    private BuildGroup resolveBuildGroup() {
        if (buildGroup == null) {
            if (context == null)
                throw new IllegalStateException(
                    "DbbBuildMapClient: BuildContext not injected — call setContext(context) before use")
            buildGroup = context.get('BUILD_GROUP') as BuildGroup
            if (!buildGroup)
                throw new IllegalStateException(
                    "BUILD_GROUP not found in BuildContext for group '${buildGroupName}'")
            log.debug("DbbBuildMapClient: resolved BuildGroup '{}' from context", buildGroupName)
        }
        return buildGroup
    }

    /**
     * Returns the output PDS members produced from {@code sourcePath} in the build map
     * stored under that path within the {@link BuildGroup} from the running context.
     *
     * @param sourcePath  Repository-relative source file path (the build map label).
     * @return            List of {@code {library, member}} maps; empty if no record is found.
     */
    List<Map<String, String>> getGeneratedObjects(String sourcePath) {
        try {
            BuildMap bm = resolveBuildGroup().getBuildMap(sourcePath)
            if (!bm) {
                log.debug("getGeneratedObjects: no build map entry for '{}'", sourcePath)
                return []
            }

            def result = bm.getOutputs()
                .findAll { it.getDataset() && it.getMember() }
                .collect { [library: it.getDataset(), member: it.getMember()] }
            log.debug("getGeneratedObjects: '{}' -> {} object(s)", sourcePath, result.size())
            return result

        } catch (BuildException e) {
            log.warn("getGeneratedObjects: BuildException for '{}': {}", sourcePath, e.message)
            return []
        }
    }
}

// --- DeleteCassaforteLogic.groovy ---
/**
 * Core business logic for deleting members from cassaforte (staging) PDS libraries.
 *
 * <p>For each source file to process, the caller provides its path, resolved file type,
 * environment stage code, system identifier, and DBB build group.  This class:
 * <ol>
 *   <li>Filters the loaded {@link DeletionRule} list by matching the file type against
 *       each rule's {@code typePattern} via {@link PatternMatcher}.</li>
 *   <li>Resolves the target PDS name from the rule's {@code libraryTemplate} using
 *       {@link LibraryNameResolver}.</li>
 *   <li>Determines the PDS member name — either directly from the source filename, or
 *       by querying the {@link BuildMapClient} when {@code useBuildMap = true}.</li>
 *   <li>Calls {@link FileService#delete} on each matching member that exists.</li>
 * </ol>
 *
 * <p>This class has zero IBM/DBB imports; all environment interaction is injected
 * via the {@link FileService} and {@link BuildMapClient} traits.
 *
 * @see DeletionRule
 * @see SfilamentoLogic
 * @see PrevEnvCleanLogic
 */
@Slf4j
class DeleteCassaforteLogic {
    FileService          ops
    List<DeletionRule>  rules
    BuildMapClient      buildMap
    PatternMatcher      matcher  = new PatternMatcher()
    LibraryNameResolver resolver = new LibraryNameResolver()

    // vars map must contain C1STAGE, C1SYSTEM, HLQ — resolved by caller per source file.
    // Returns number of delete operations performed.
    int execute(String sourcePath, String fileType, Map<String,String> vars, String buildGroup) {
        def member   = memberName(sourcePath)
        def matching = rules.findAll { matcher.matches(it.typePattern, fileType) }
        log.debug("execute: sourcePath='{}' fileType='{}' buildGroup='{}' matchingRules={}",
                  sourcePath, fileType, buildGroup, matching.size())
        int count    = 0

        matching.each { rule ->
            def lib = resolver.resolve(rule.libraryTemplate, vars)
            if (rule.useBuildMap) {
                buildMap.getGeneratedObjects(sourcePath).each { obj ->
                    def zp = "//${lib}(${obj.member})"
                    if (ops.exists(zp)) {
                        log.info("Deleting (build-map): {}", zp)
                        ops.delete(zp)
                        count++
                    }
                }
            } else {
                def zp = "//${lib}(${member})"
                if (ops.exists(zp)) {
                    log.info("Deleting: {}", zp)
                    ops.delete(zp)
                    count++
                }
            }
        }
        log.debug("execute: {} deletion(s) performed for '{}'", count, sourcePath)
        count
    }

    static String memberName(String sourcePath) {
        def filename = sourcePath.tokenize('/').last()
        def name = filename.contains('.') ? filename.take(filename.lastIndexOf('.')) : filename
        name.toUpperCase()
    }
}

// --- DeletionRule.groovy ---
/**
 * Immutable value object representing one row from the deletion-rules CSV file.
 *
 * <p>Fields:
 * <ul>
 *   <li>{@code typePattern}     — member-type glob matched against the source file type
 *                                 ({@code %} = exactly one char, {@code *} = zero or more).</li>
 *   <li>{@code libraryTemplate} — parametric PDS name with {@code ${C1STAGE}} / {@code ${C1SYSTEM}}
 *                                 placeholders resolved at runtime by {@link LibraryNameResolver}.</li>
 *   <li>{@code useBuildMap}     — when {@code true}, the generated object name is resolved via the
 *                                 DBB build map instead of being derived directly from the source name.</li>
 * </ul>
 *
 * @see DeletionRulesLoader
 * @see PatternMatcher
 * @see LibraryNameResolver
 */
@groovy.transform.Immutable
class DeletionRule {
    String typePattern
    String libraryTemplate
    boolean useBuildMap
}

// --- DeletionRulesLoader.groovy ---
/**
 * Reads the deletion-rules CSV file and converts each non-blank, non-comment line
 * into a {@link DeletionRule} instance consumed by the cassaforte cleanup logic.
 *
 * <p>Expected CSV format (semicolon-separated, 3 fields):
 * <pre>
 *   &lt;type-pattern&gt;;&lt;parametric-library&gt;;&lt;flag&gt;
 * </pre>
 * <ul>
 *   <li>{@code type-pattern}   — member-type glob ({@code %} = one char, {@code *} = any chars)</li>
 *   <li>{@code parametric-library} — target PDS template, may contain {@code ${C1STAGE}} / {@code ${C1SYSTEM}}</li>
 *   <li>{@code flag}           — {@code NO} to delete by source name;
 *                                {@code BUILD MAP} to resolve the generated object name via DBB build map</li>
 * </ul>
 *
 * <p>Lines starting with {@code #} are treated as comments and skipped.
 *
 * @see DeletionRule
 * @see scripts/build-data/rules.csv
 */
@Slf4j
class DeletionRulesLoader {

    List<DeletionRule> load(File file) {
        log.debug("Loading deletion rules from: {}", file)
        def result = file.readLines()
            .findAll { it.trim() && !it.startsWith('#') }
            .collect { line ->
                def parts = line.split(';', -1)
                if (parts.size() < 3)
                    throw new IllegalArgumentException("Invalid rule (need 3 semicolon-separated fields): '$line'")
                new DeletionRule(
                    typePattern:     parts[0].trim(),
                    libraryTemplate: parts[1].trim(),
                    useBuildMap:     parts[2].trim() == 'BUILD MAP'
                )
            }
        log.info("Loaded {} deletion rules from: {}", result.size(), file)
        result
    }
}

// --- EnvironmentChain.groovy ---
/**
 * Models the ISP build pipeline's ordered environment chain and the relationships
 * between environments used by the cassaforte cleanup scripts.
 *
 * <h3>Environment chain</h3>
 * <pre>
 *   ATI → ATO → ST → PR
 *   EM  (standalone, no predecessor)
 * </pre>
 *
 * <h3>Stage codes (C1STAGE)</h3>
 * <pre>
 *   ATI → I1 | ATO → O1 | ST → S1 | PR → P1 | EM → E1
 * </pre>
 *
 * <h3>Key relationships</h3>
 * <ul>
 *   <li><b>Predecessor</b> ({@link #getPredecessor}): the environment immediately before in
 *       the chain; used by {@link PrevEnvCleanLogic} to delete stale cassaforte members
 *       after a successful build.</li>
 *   <li><b>Superiors</b> ({@link #getSuperiors}): environments further ahead in the chain
 *       that may hold a stable copy to restore from; used by {@link SfilamentoLogic}.</li>
 * </ul>
 *
 * <h3>Capability flags</h3>
 * <ul>
 *   <li>{@link #requiresPrevEnvClean} — true for ST and PR (they have a predecessor).</li>
 *   <li>{@link #supportsSfilamento}   — true only for ST (the SAD restore step).</li>
 * </ul>
 */
@Slf4j
class EnvironmentChain {

    static final Map<String, String> PREDECESSORS = [
        ST: 'ATO',
        PR: 'ST',
    ]

    static final Map<String, List<String>> SUPERIORS = [
        ST:  ['PR'],
        ATI: ['ATO'],
        ATO: ['ST'],
    ]

    // TODO: verify EM and SDD stage codes against actual ISP build configuration.
    static final Map<String, String> STAGE_BY_ENV = [
        ATI: 'I1',
        ATO: 'O1',
        ST:  'S1',
        PR:  'P1',
        EM:  'E1',
    ]

    String getPredecessor(String env) {
        PREDECESSORS[env?.toUpperCase()]
    }

    List<String> getSuperiors(String env) {
        SUPERIORS[env?.toUpperCase()] ?: []
    }

    String getStage(String env) {
        def stage = STAGE_BY_ENV[env?.toUpperCase()]
        if (!stage) {
            log.error("Unknown environment: '{}'", env)
            throw new IllegalArgumentException("Unknown environment: '${env ?: 'null'}'")
        }
        stage
    }

    boolean requiresPrevEnvClean(String env) {
        env?.toUpperCase() in PREDECESSORS.keySet()
    }

    boolean supportsSfilamento(String env) {
        env?.toUpperCase() == 'ST'
    }
}

// --- FileService.groovy ---
/**
 * Trait (interface) that abstracts z/OS PDS member operations for cassaforte cleanup logic.
 *
 * <p>Operates only on PDS/PDSE members. Dataset-level operations (allocation, deletion of entire datasets)
 * are out of scope. Unix/USS filesystem paths are not supported; all paths must use z/OS syntax.
 *
 * <p>Path format (required):
 * <pre>
 *   //DATASET.NAME(MEMBER)  — PDS/PDSE member (required; no plain dataset or Unix path references)
 * </pre>
 *
 * <p>Three implementations provided:
 * <ul>
 *   <li>{@link MacosFileService}  — simulates z/OS PDS on local filesystem for unit testing (macOS/Linux).</li>
 *   <li>{@link UssFileService}    — simulates z/OS PDS on USS filesystem (z/OS).</li>
 *   <li>{@link JzosFileService}   — delegates to IBM JZOS {@code ZFile} and {@code PdsDirectory} on z/OS USS.</li>
 * </ul>
 *
 * All operations require a member component and will throw {@link IllegalArgumentException} on
 * dataset-only or non-z/OS path references.
 */
@Slf4j
trait FileService {

    // all member only
    abstract boolean exists(String path)
    abstract void    delete(String path)
    abstract void    copy(String src, String dst)
    abstract List<String> list(String dsn)
}

// --- JsonBuildMapClient.groovy ---
/**
 * JSON-file implementation of {@link BuildMapClient} used during unit testing and local dev.
 *
 * <p>Reads a pre-captured DBB build-map JSON file (see {@code src/test/resources/fixtures/buildmap.json})
 * and returns the list of generated output objects for a given source path and build group.
 *
 * <p>The JSON file is an array of DBB build-map entries, each with {@code buildFile}, {@code group},
 * and {@code outputs} (list of {@code {member, dataset}} objects) — matching the structure of the
 * real DBB build map API response.  A single-object file is also accepted.
 *
 * <p>This class has no IBM/DBB dependencies and can run in any standard JVM.
 * Build map path is read from {@link PuliziaCassaforteConfig#buildMapPath}.
 *
 * @see BuildMapClient
 * @see MacosFileService
 */
@Slf4j
class JsonBuildMapClient extends BuildMapClient {
    private final List data

    JsonBuildMapClient(String buildGroupName, PuliziaCassaforteConfig cfg) {
        this.buildGroupName = buildGroupName
        def parsed = new JsonSlurper().parse(new File(cfg.buildMapPath))
        data = (parsed instanceof List) ? parsed : [parsed]
        log.debug("Loaded {} build map entries from: {}", data.size(), cfg.buildMapPath)
    }

    List<Map<String, String>> getGeneratedObjects(String sourcePath) {
        def entry = data.find { it.buildFile == sourcePath && it.group == buildGroupName }
        if (!entry) {
            log.debug("getGeneratedObjects: no entry for '{}' in group '{}'", sourcePath, buildGroupName)
            return []
        }
        def result = ((entry.outputs ?: []) as List)
            .findAll { it.dataset && it.member }
            .collect { [library: it.dataset as String, member: it.member as String] }
        log.debug("getGeneratedObjects: '{}' group '{}' -> {} object(s)", sourcePath, buildGroupName, result.size())
        result
    }
}

// --- JzosFileService.groovy ---
// Mainframe-only. Must be compiled and run with groovyz on z/OS USS.
// After upload to USS: chtag -tc IBM-1047 JzosFileService.groovy
// ZFile javadoc https://www.ibm.com/docs/en/sdk-java-technology/8?topic=jzos-zfile


/**
 * z/OS PDS/PDSE member operations, implementing the member-only {@link FileService} trait.
 *
 * Every operation acts on a partitioned dataset member. References use the form:
 *
 *   //DSN(MEMBER)   or   DSN(MEMBER)     — a single member (exists / delete / copy)
 *   //DSN           or   DSN             — the library itself (list)
 *
 * A leading {@code //} is optional and stripped; the dataset name is always treated as
 * fully qualified (no userid prefix is added). exists / delete / copy reject a reference
 * without a member component, since this service does not perform dataset-level operations.
 *
 * Disposition: every path here is either a directory read or a member STOW, so DISP=SHR is
 * always the correct choice.
 *   - exists / list / copy-source  -> input open => SHR implicitly.
 *   - delete / copy-target         -> the library is pre-allocated SHR and the member is
 *                                     driven through a //DD: reference, so LE reuses the SHR
 *                                     allocation instead of taking its default exclusive
 *                                     (OLD) lock. STOW serializes the directory update.
 *
 * Compiled against JZOS stubs (compileOnly) so it builds locally without IBM jars.
 * At runtime on z/OS USS the real JZOS classes must be on the classpath.
 */
@Slf4j
class JzosFileService implements FileService {

    /** 32760 = max payload of a RECFM=VB block (0x7FF8); safe upper bound for any LRECL. */
    private static final int MAX_RECORD = 32760

    /** Per-JVM counter for unique DD names; avoids S99ERROR 0x410 on concurrent/retried ops. */
    private static final AtomicInteger DD_SEQ = new AtomicInteger()

    /**
     * True if {@code MEMBER} exists in the PDS named by {@code path} (//DSN(MEMBER)).
     *
     * Uses {@link ZFile#exists(String)}, which for a member reference reads the PDS
     * directory (input open => SHR). No exclusive allocation is taken.
     */
    boolean exists(String path) {
        def (dsn, member) = parse(path)
        requireMember(member, 'exists', path)
        boolean result
        try {
            result = ZFile.exists("//'${dsn}(${member})'")
        } catch (ZFileException ignored) {
            // Older JZOS levels could throw instead of returning false (APAR PM64118).
            result = false
        }
        log.debug('exists({}): {}', path, result)
        return result
    }

    /**
     * Deletes {@code MEMBER} from the PDS named by {@code path} (//DSN(MEMBER)).
     *
     * A member delete is a STOW DELETE on the directory, performed under DISP=SHR via a
     * //DD: reference so the whole library is not locked.
     */
    void delete(String path) {
        log.debug('delete({})', path)
        def (dsn, member) = parse(path)
        requireMember(member, 'delete', path)
        withShrDd(dsn) { String dd ->
            ZFile.remove("//DD:${dd}(${member})")
        }
    }

    /**
     * Copies a member from one PDS to another (or to a different member of the same PDS).
     * Both {@code src} and {@code dst} must be member references.
     *
     * Records are copied one logical record at a time with rb/wb + type=record, preserving
     * RECFM and record boundaries with no EBCDIC<->ASCII translation. The source opens for
     * input (SHR); the target member is written through a SHR-allocated //DD: reference, so
     * the target library is not exclusively locked. Both libraries must already exist and be
     * attribute-compatible.
     */
    void copy(String src, String dst) {
        log.debug('copy({} -> {})', src, dst)
        def (srcDsn, srcMember) = parse(src)
        def (dstDsn, dstMember) = parse(dst)
        requireMember(srcMember, 'copy(source)', src)
        requireMember(dstMember, 'copy(target)', dst)

        ZFile srcFile = new ZFile("//'${srcDsn}(${srcMember})'", 'rb,type=record')
        try {
            withShrDd(dstDsn) { String dd ->
                writeRecords(srcFile, "//DD:${dd}(${dstMember})")
            }
        } finally {
            srcFile.close()
        }
    }

    /**
     * Lists the members of the PDS/PDSE named by {@code dsn}, equivalent to
     * {@code tsocmd "LISTDS '<dsn>' MEMBERS"}. A leading {@code //} and any accidental
     * member component are tolerated and ignored. Members come back in directory order
     * (ascending by name), which is the order LISTDS reports; aliases are included.
     *
     * The directory is read with an input open (SHR). A sequential dataset, or a name that
     * cannot be opened as a directory, yields a clear IllegalArgumentException.
     */
    List<String> list(String dsn) {
        String lib = parse(dsn)[0]
        def members = []
        PdsDirectory dir
        try {
            dir = new PdsDirectory("//'${lib}'")   // input open => SHR
        } catch (ZFileException e) {
            throw new IllegalArgumentException(
                    "Cannot list '${lib}': not a partitioned dataset, or not found", e)
        }
        try {
            for (MemberInfo mi : dir) {
                members << mi.getName()             // mi.isAlias() available if filtering is wanted
            }
        } finally {
            dir.close()
        }
        log.debug('list({}): {} member(s)', dsn, members.size())
        return members
    }

    // ─── private helpers ──────────────────────────────────────────────────────

    /**
     * Allocates {@code dsn} with DISP=SHR to a unique DD, runs {@code body} with that DD
     * name, and unconditionally frees the DD afterwards. The unique DD name prevents the
     * S99ERROR 0x410 ("ddname already allocated") that a hardcoded name would cause on
     * concurrent or retried operations. A failure to free is logged, never propagated, so
     * it cannot mask the real outcome of {@code body}.
     */
    private void withShrDd(String dsn, Closure body) {
        String dd = uniqueDd()
        ZFile.bpxwdyn("alloc fi(${dd}) da('${dsn}') shr msg(2)")
        try {
            body.call(dd)
        } finally {
            try {
                ZFile.bpxwdyn("free fi(${dd})")
            } catch (Exception e) {
                log.warn('Failed to free DD {}: {}', dd, e.message)
            }
        }
    }

    /** Copies all logical records from an already-open source into {@code dstSpec}. */
    private void writeRecords(ZFile srcFile, String dstSpec) {
        ZFile dstFile = new ZFile(dstSpec, 'wb,type=record')
        try {
            byte[] buf = new byte[MAX_RECORD]
            int len
            // read() returns one record's length, or -1 at EOF; 0 is a valid empty record.
            while ((len = srcFile.read(buf)) >= 0) {
                dstFile.write(buf, 0, len)
            }
        } finally {
            dstFile.close()
        }
    }

    /** DD name "DDnnnnnn" (8 chars, leading alpha, hex suffix — all valid DD characters). */
    private String uniqueDd() {
        String.format('DD%06X', DD_SEQ.incrementAndGet() & 0xFFFFFF)
    }

    /**
     * Parses a reference into [dsn, member]; member is null when absent. A leading {@code //}
     * is optional.
     *   //MY.PDS(MBR)  -> ['MY.PDS', 'MBR']
     *   MY.PDS(MBR)    -> ['MY.PDS', 'MBR']
     *   //MY.PDS       -> ['MY.PDS', null]
     */
    private List<String> parse(String ref) {
        String s = ref.startsWith('//') ? ref.substring(2) : ref
        def m = (s =~ /^(.+?)\((.+?)\)$/)
        m.matches() ? [m.group(1), m.group(2)] : [s, null]
    }

    /** Enforces the member-only contract for exists / delete / copy. */
    private void requireMember(String member, String op, String ref) {
        if (!member) {
            throw new IllegalArgumentException(
                    "${op} requires a PDS member reference like //DSN(MEMBER), got: ${ref}")
        }
    }
}

// --- LibraryNameResolver.groovy ---
/**
 * Resolves parametric PDS library names by substituting ISP stage and system tokens,
 * and derives TOCOLB library names from cassaforte library names.
 *
 * <h3>Template substitution</h3>
 * <p>Library templates stored in the deletion-rules CSV may contain two placeholders:
 * <ul>
 *   <li>{@code ${C1STAGE}}  — the two-character stage code for the target environment
 *                             (e.g. {@code I1}, {@code O1}, {@code S1}, {@code P1}).</li>
 *   <li>{@code ${C1SYSTEM}} — the application system identifier (e.g. {@code YN}).</li>
 * </ul>
 *
 * <h3>TOCOLB derivation</h3>
 * <p>The sfilamento restore target (TOCOLB library) is computed by transforming qualifiers
 * 4 and 5 (1-based) of the resolved cassaforte library name:
 * <pre>
 *   qualifier 4: replaces the pattern {@code @@@@}     with {@code TO@@}
 *   qualifier 5: replaces the pattern {@code @@@@@@@@} with {@code COLB@@@@}
 * </pre>
 *
 * @see DeletionRule#libraryTemplate
 * @see SfilamentoLogic
 */
@Slf4j
class LibraryNameResolver {
    String resolve(String template, Map<String, String> vars) {
        def result = vars.inject(template) { acc, key, val ->
            acc.replace('${' + key + '}', val ?: '')
        }
        def unresolved = (result =~ /\$\{[^}]+\}/)
        if (unresolved) {
            log.error("Unresolved macro: {} in template: '{}'", unresolved[0], template)
            throw new IllegalStateException(
                "Unresolved macro: ${unresolved[0]} in template: '${template}'"
            )
        }
        log.debug("resolve: '{}' -> '{}'", template, result)
        result
    }

    // Derives TOCOLB library from resolved cassaforte library.
    // 4th qualifier '@@@@' → 'TO@@', 5th qualifier '@@@@@@@@' → 'COLB@@@@'.
    String toTocolbLibrary(String resolvedLibrary) {
        def parts = resolvedLibrary.split('\\.', -1)
        if (parts.size() >= 5) {
            parts[3] = parts[3].replace('@@@@', 'TO@@')
            parts[4] = parts[4].replace('@@@@@@@@', 'COLB@@@@')
        }
        def result = parts.join('.')
        log.debug("toTocolbLibrary: '{}' -> '{}'", resolvedLibrary, result)
        result
    }
}

// --- MacosFileService.groovy ---
/**
 * macOS/local-dev adapter of the {@link FileService} trait used during unit testing.
 *
 * <p>Simulates a z/OS PDS environment by mapping z/OS-style dataset paths onto ordinary
 * directories under a configurable {@code baseDir} (default: {@code /tmp/zos-sim/}):
 * <pre>
 *   //DATASET.NAME(MEMBER)  →  &lt;baseDir&gt;/DATASET.NAME/MEMBER   (PDS member = file)
 *   //DATASET.NAME          →  &lt;baseDir&gt;/DATASET.NAME           (PDS = directory)
 * </pre>
 *
 * <p>Only z/OS syntax (//DSN(MEMBER)) is supported. Unix paths are rejected with
 * {@link IllegalArgumentException}. Uses {@link java.nio.file.Files} for all I/O — no IBM/DBB dependencies.
 * Tests inject a JUnit 5 {@code @TempDir} as {@code baseDir} for full isolation.
 *
 * @see FileService
 * @see UssFileService
 * @see JzosFileService
 */
@Slf4j
class MacosFileService implements FileService {

    final String baseDir

    MacosFileService(String baseDir = '/tmp/zos-sim') {
        this.baseDir = baseDir
        log.debug("MacosFileService initialized with baseDir: {}", baseDir)
    }

    /**
     * Parses a z/OS path into [dsn, member].
     * Member is null if path has no (MEMBER) component.
     * //DSN(MEMBER) → ['DSN', 'MEMBER']
     * //DSN → ['DSN', null]
     * Non-z/OS paths throw IllegalArgumentException.
     */
    private List<String> parseDsnMember(String zosPath) {
        if (!zosPath.startsWith('//')) {
            throw new IllegalArgumentException("Path must use z/OS syntax (//DSN or //DSN(MEMBER)), got: ${zosPath}")
        }
        def inner = zosPath.substring(2)
        def m = (inner =~ /^(.+?)\((.+?)\)$/) // matches DATASET(MEMBER) pattern
        m.matches() ? [m.group(1), m.group(2)] : [inner, null]
    }

    private Path resolve(String dsn, String member) {
        member ? Paths.get(baseDir, dsn, member) : Paths.get(baseDir, dsn)
    }

    boolean exists(String path) {
        def (dsn, member) = parseDsnMember(path)
        if (!member) {
            throw new IllegalArgumentException("exists() requires a member reference (//DSN(MEMBER)), got: ${path}")
        }
        def result = Files.exists(resolve(dsn, member))
        log.debug("exists({}): {}", path, result)
        result
    }

    void delete(String path) {
        log.debug("delete({})", path)
        def (dsn, member) = parseDsnMember(path)
        if (!member) {
            throw new IllegalArgumentException("delete() requires a member reference (//DSN(MEMBER)), got: ${path}")
        }
        Files.deleteIfExists(resolve(dsn, member))
    }

    void copy(String src, String dst) {
        log.debug("copy({} -> {})", src, dst)
        def (srcDsn, srcMember) = parseDsnMember(src)
        def (dstDsn, dstMember) = parseDsnMember(dst)

        if (!srcMember || !dstMember) {
            throw new IllegalArgumentException("copy() requires member references (//DSN(MEMBER)), got: src=${src} dst=${dst}")
        }

        if (srcMember != dstMember) {
            log.warn("copy({} -> {}): source member '{}' differs from destination member '{}'", src, dst, srcMember, dstMember)
        }

        def dstPath = resolve(dstDsn, dstMember)
        Files.createDirectories(dstPath.parent)
        def srcPath = resolve(srcDsn, srcMember)
        if (Files.exists(srcPath)) {
            Files.copy(srcPath, dstPath, StandardCopyOption.REPLACE_EXISTING)
        } else {
            Files.createFile(dstPath) // src absent → create empty dst, simulating a z/OS member with no content
        }
    }

    List<String> list(String container) {
        def (dsn, member) = parseDsnMember(container)
        // list() accepts member but ignores it, using only DSN
        def dir = resolve(dsn, null)
        if (!Files.isDirectory(dir)) {
            log.debug("list({}): not a directory", container)
            return []
        }
        def result = dir.toFile().list()?.toList() ?: []
        log.debug("list({}): {} member(s)", container, result.size())
        result
    }

}

// --- PathVariableExtractor.groovy ---
/**
 * Extracts per-file template variables from a source path.
 *
 * <p>Identifies the application segment in the path (the component whose
 * underscore-delimited tokens satisfy {@code tokens[2] =~ /\d+/}), then
 * looks up the C1STAGE in the stage map using {@code PATH_LO|buildEnv}.
 *
 * <p>Returns a map with keys {@code C1STAGE}, {@code C1SYSTEM}, {@code HLQ}.
 *
 * @see StageMapLoader
 * @see LibraryNameResolver
 */
@Slf4j
class PathVariableExtractor {

    // Jobz (fileType 'STWSNCS','STWSJGO','STWSJGM') paths have no application segment; 
    // layer operativo is always '01' and C1SYSTEM is not applicable.
    // Jobz extensions are set as a default in PuliziaCassaforteConfig 
    // and can be overridden via properties or test code.
    Map<String, String> extractJobz(String buildEnv, Map<String, String> stageMap, String hlq, String fileType) {
        def key = "01|${buildEnv}"
        // if fileType is STWSNCS, STWSJGO, or STWSJGM and buildEnv is PR then set key to fileType|PR
        if (fileType in ['STWSNCS', 'STWSJGO'] && buildEnv == 'PR') {
            key = "${fileType}|${buildEnv}"
            log.trace("extractJobz: special case for fileType='{}' and buildEnv='{}', using key='{}'", fileType, buildEnv, key)
        }
        def c1stagep = stageMap[key]
        if (!c1stagep)
            throw new IllegalArgumentException(
                "No stage-map entry for '${key}' (jobz path, env='${buildEnv}')"
            )
        def result = [C1STAGE: c1stagep, C1STAGEP: c1stagep, C1SYSTEM: '', HLQ: hlq ?: '']
        log.debug("extractJobz (special case): env='{}' C1STAGE='{}' C1STAGEP='{}' HLQ='{}'", 
                    buildEnv, c1stagep, c1stagep, hlq)
        return result
    }

    Map<String, String> extract(String sourcePath, String buildEnv,
                                Map<String, String> stageMap, String hlq) {
        def segment = sourcePath.tokenize('/').find { part ->
            def tokens = part.split('_')
            tokens.size() >= 5 && tokens[2] ==~ /\d+/
        }
        if (!segment)
            throw new IllegalArgumentException(
                "No application segment found in source path: '${sourcePath}'"
            )

        def tokens   = segment.split('_')
        def c1system = tokens[1]
        def pathLo   = tokens[2]
        def key      = "${pathLo}|${buildEnv}"
        def c1stage  = stageMap[key]
        if (!c1stage)
            throw new IllegalArgumentException(
                "No stage-map entry for '${key}' (path: '${sourcePath}')"
            )

        def result = [C1STAGE: c1stage, C1SYSTEM: c1system, HLQ: hlq ?: '']
        log.debug("extract: path='{}' env='{}' -> C1STAGE='{}' C1SYSTEM='{}' HLQ='{}'",
                  sourcePath, buildEnv, c1stage, c1system, hlq)
        result
    }
}

// --- PatternMatcher.groovy ---
/**
 * Converts z/OS-style glob patterns to regular expressions and tests whether a value matches.
 *
 * <p>Supported wildcards (aligned with the ISP deletion-rules convention):
 * <ul>
 *   <li>{@code %} — matches exactly one character (equivalent to regex {@code .}).</li>
 *   <li>{@code *} — matches zero or more characters (equivalent to regex {@code .*}).</li>
 * </ul>
 *
 * All other characters are treated as literals.
 *
 * <p>Example: pattern {@code SJCL*} matches {@code SJCL}, {@code SJCLLOAD}, {@code SJCL123},
 * while {@code S%CL} matches only four-character strings starting with S and ending with CL.
 *
 * @see DeletionRule#typePattern
 */
@Slf4j
class PatternMatcher {
    boolean matches(String pattern, String value) {
        def regex = pattern.trim().collect { c ->
            switch (c) {
                case '%': return '.'
                case '*': return '.*'
                default:  return Pattern.quote(String.valueOf(c))
            }
        }.join('')
        def result = value.trim() ==~ regex
        log.trace("matches('{}', '{}') = {}", pattern, value, result)
        result
    }
}

// --- PrevEnvCleanLogic.groovy ---
/**
 * DBB post-build task logic: deletes the corresponding cassaforte member from the
 * <em>predecessor</em> environment after a successful compile step.
 *
 * <h3>Purpose</h3>
 * <p>When a source is promoted from environment N-1 to N, the N-1 cassaforte library
 * may still contain a stale copy of the old object.  If the N-1 library participates in
 * a concatenation with N, the stale entry shadows the new one.  This logic removes it
 * so that the concatenation always resolves to the most recently promoted version.
 *
 * <h3>Applicability</h3>
 * <p>Runs only in environments that have a predecessor
 * ({@link EnvironmentChain#requiresPrevEnvClean}): currently {@code ST} and {@code PR}.
 * Returns 0 immediately for all other environments (ATI, ATO, EM).
 *
 * @see DeleteCassaforteLogic
 * @see EnvironmentChain#requiresPrevEnvClean
 * @see EnvironmentChain#getPredecessor
 */
@Slf4j
class PrevEnvCleanLogic {
    DeleteCassaforteLogic deleteLogic
    PathVariableExtractor extractor  = new PathVariableExtractor()
    Map<String, String>   stageMap   = [:]
    String                hlq        = ''
    EnvironmentChain      envChain   = new EnvironmentChain()

    int execute(String sourcePath, String fileType, String environment, String buildGroup) {
        if (!envChain.requiresPrevEnvClean(environment)) {
            log.debug("Skipping prevEnvClean for environment '{}' (no predecessor)", environment)
            return 0
        }
        def prevEnv  = envChain.getPredecessor(environment)
        log.info("Cleaning predecessor '{}' cassaforte for sourcePath='{}'", prevEnv, sourcePath)
        def prevVars = extractor.extract(sourcePath, prevEnv, stageMap, hlq)
        deleteLogic.execute(sourcePath, fileType, prevVars, buildGroup)
    }
}

// --- PuliziaCassaforteConfig.groovy ---
/**
 * Configuration parsed from a {@link Properties} object for {@link PuliziaCassaforteImpl}.
 *
 * <p>Separates the "read config" concern from execution logic.  All fields are
 * {@code null} when the corresponding property key is absent — callers distinguish
 * "not set" from any default value.</p>
 *
 * <p>Property values may contain {@code ${VAR}} or {@code $VAR} placeholders resolved
 * against process environment variables before assignment.</p>
 *
 * <p>Configuration supports both testing using a local filesystem (non z/OS) 
 * and using a build map provided as a JSON file, by setting the appropriate {@code fileOpsType} 
 * and {@code buildMapClientType} values.</p>
 */
class PuliziaCassaforteConfig {

    // Sensible defaults for ease of use on USS, where properties files are less convenient.  
    // These can be overridden by properties files or test code.
    String fileOpsType        = 'zos' // 'zos', 'uss', or 'macos'
    String buildMapClientType = 'db2' // 'db2', 'dbb', 'json'
    String userId             = null
    String pwFilePath         = null
    String db2ConfigPath      = null
    String buildMapPath       = null
    String uxBasedir          = null
    String hlq                = null
    /** {@code null} when the {@code jobzExtensions} key is absent from the properties. */
    Set<String> jobzExtensions = ['STWSNCS','STWSJGO','STWSJGM'] as Set
    String rulesPath          = 'build-data/rules.csv'
    String stageMapPath       = 'build-data/stagemap.csv'
    String buildGroupName     = null

    /**
     * Build a config by expanding env-var placeholders in {@code props} and mapping
     * the known keys.  Unknown keys are silently ignored.
     */
    static PuliziaCassaforteConfig from(Properties props) {
        Properties resolved = new Properties()
        props.each { k, v ->
            def expanded = expandEnvVars(v?.toString())
            if (expanded != null) resolved.setProperty(k.toString(), expanded)
        }

        def cfg = new PuliziaCassaforteConfig()
        cfg.fileOpsType        = resolved.getProperty('fileOpsType')        ?: cfg.fileOpsType
        cfg.buildMapClientType = resolved.getProperty('buildMapClientType') ?: cfg.buildMapClientType
        cfg.rulesPath          = resolved.getProperty('rulesPath')          ?: cfg.rulesPath
        cfg.stageMapPath       = resolved.getProperty('stageMapPath')       ?: cfg.stageMapPath
        cfg.uxBasedir          = resolved.getProperty('uxBasedir')          ?: cfg.uxBasedir
        cfg.hlq                = resolved.getProperty('hlq')                ?: cfg.hlq
        cfg.userId             = resolved.getProperty('userId')             ?: cfg.userId
        cfg.pwFilePath         = resolved.getProperty('pwFilePath')         ?: cfg.pwFilePath
        cfg.db2ConfigPath      = resolved.getProperty('db2ConfigPath')      ?: cfg.db2ConfigPath
        cfg.buildMapPath       = resolved.getProperty('buildMapPath')       ?: cfg.buildMapPath
        if (resolved.getProperty('jobzExtensions')) {
            cfg.jobzExtensions = resolved.getProperty('jobzExtensions')
                .split(',').collect { it.trim().toUpperCase() }.findAll { it }.toSet()
        }
        return cfg
    }

    /**
     * Validates the configuration according to the following rules:
     * <ul>
     *   <li>{@code rulesPath} and {@code stagemapPath} must be set and point to existing files.</li>
     *   <li>When {@code buildMapClientType} is {@code db2}: {@code userId}, {@code pwFilePath}
     *       and {@code db2ConfigPath} must all be non-null, and their paths must exist.</li>
     *   <li>When {@code buildMapClientType} is {@code json}: {@code buildMapPath} must be set
     *       and point to an existing file.</li>
     * </ul>
     * @throws IllegalArgumentException on the first rule violation found.
     */
    void validate() {
        if (!rulesPath)
            throw new IllegalArgumentException('rulesPath must be defined in config')
        if (!new File(rulesPath).exists())
            throw new IllegalArgumentException("rulesPath not found: '$rulesPath'")
        if (!stageMapPath)
            throw new IllegalArgumentException('stageMapPath must be defined in config')
        if (!new File(stageMapPath).exists())
            throw new IllegalArgumentException("stageMapPath not found: '$stageMapPath'")

        def bmType = buildMapClientType ?: 'db2'
        if (bmType == 'db2') {
            int credCount = [userId, pwFilePath, db2ConfigPath].count { it }
            if (credCount == 0)
                throw new IllegalArgumentException('db2 buildMapClientType requires userId, pwFilePath and db2ConfigPath')
            if (credCount < 3)
                throw new IllegalArgumentException('userId, pwFilePath and db2ConfigPath must all be defined or none')
            if (!new File(pwFilePath).exists())
                throw new IllegalArgumentException("pwFilePath not found: '$pwFilePath'")
            if (!new File(db2ConfigPath).exists())
                throw new IllegalArgumentException("db2ConfigPath not found: '$db2ConfigPath'")
        } else if (bmType == 'json') {
            if (!buildMapPath)
                throw new IllegalArgumentException('json buildMapClientType requires buildMapPath')
            if (!new File(buildMapPath).exists())
                throw new IllegalArgumentException("buildMapPath not found: '$buildMapPath'")
        } else {
            throw new IllegalArgumentException("Unknown buildMapClientType: '$bmType'")
        }
    }

    /**
     * Expands {@code ${VAR}} and {@code $VAR} references using process environment variables.
     * Unresolved references (env var not set) are kept verbatim.
     */
    static String expandEnvVars(String value) {
        if (!value) return value
        value.replaceAll(/\$\{([A-Za-z_][A-Za-z0-9_]*)\}|\$([A-Za-z_][A-Za-z0-9_]*)/) { List<String> m ->
            String varName = m[1] ?: m[2]
            System.getenv(varName) ?: m[0]
        }
    }
}

// --- PuliziaCassaforteImpl.groovy ---
/**
 * Business logic for the {@code PuliziaCassaforte.groovy} entry point.
 *
 * <p>Compiled into {@code pulizia-cassaforte.jar} so it is available on both USS
 * (via {@code groovyz}) and local dev (via {@code groovy}).  Has no IBM/DBB compile-time
 * dependencies — IBM types are accessed via reflection where needed.
 *
 * @see DeleteCassaforteLogic
 * @see SfilamentoLogic
 */
@Slf4j
class PuliziaCassaforteImpl {

    String fileOpsType        = null
    String buildMapClientType = null

    // Used by db2 build map client
    String userId             = null
    String pwFilePath         = null
    String db2ConfigPath      = null

    // Used by JSON build map client
    String buildMapPath       = null

    // Used by UssFileService/MacosFileService when fileOpsType is 'uss' or 'macos'
    String uxBasedir          = null

    // Used by JzosFileService if fileOpsType is set to 'zos'
    String hlq                = null

    Set<String> jobzExtensions = [] as Set

    // Default paths to rules and stage map CSVs. Override in tests or when running on USS.
    String rulesPath          = null
    File   rulesFile          = null
    String stagemapPath       = null
    File   stageMapFile       = null

    BuildMapClient buildMapClient = null
    FileService fileOps = null

    List rules                      = null
    Map stageMap                    = null
    PathVariableExtractor extractor = null
    EnvironmentChain envChain       = null
    DeleteCassaforteLogic deleteLogic = null
    SfilamentoLogic sfilamento    = null

    int doPuliziaCassaforte(File listToProcess, String environment, String buildGroup, String configFile = 'PuliziaCassaforte.properties') {
        Properties props = new Properties()
        new File(configFile).withInputStream { props.load(it) }
        return doPuliziaCassaforte(listToProcess, environment, buildGroup, props)
    }

    int doPuliziaCassaforte(File listToProcess, String environment, String buildGroup, Properties props) {
        log.info("Starting PuliziaCassaforte")
        def cfg = PuliziaCassaforteConfig.from(props)
        if (cfg.fileOpsType)                   this.fileOpsType        = cfg.fileOpsType
        if (cfg.buildMapClientType)            this.buildMapClientType = cfg.buildMapClientType
        if (props.containsKey('rulesPath'))    this.rulesPath          = cfg.rulesPath
        if (props.containsKey('stageMapPath')) this.stagemapPath       = cfg.stageMapPath
        if (cfg.uxBasedir)          this.uxBasedir          = cfg.uxBasedir
        if (cfg.hlq)                this.hlq                = cfg.hlq
        if (cfg.userId)             this.userId             = cfg.userId
        if (cfg.pwFilePath)         this.pwFilePath         = cfg.pwFilePath
        if (cfg.db2ConfigPath)      this.db2ConfigPath      = cfg.db2ConfigPath
        if (cfg.buildMapPath)       this.buildMapPath       = cfg.buildMapPath
        if (cfg.jobzExtensions != null) this.jobzExtensions = cfg.jobzExtensions

        if (!listToProcess)
            throw new IllegalArgumentException('listToProcess argument is required')
        if (!listToProcess.exists())
            throw new IllegalArgumentException("listToProcess file not found: '$listToProcess'")

        def effectiveCfg = new PuliziaCassaforteConfig(
            buildMapClientType: this.buildMapClientType,
            rulesPath:          this.rulesPath,
            stageMapPath:       this.stagemapPath,
            buildMapPath:       this.buildMapPath,
            userId:             this.userId,
            pwFilePath:         this.pwFilePath,
            db2ConfigPath:      this.db2ConfigPath
        )
        effectiveCfg.validate()

        rulesFile    = new File(rulesPath)
        stageMapFile = new File(stagemapPath)

        switch (this.buildMapClientType) {
            case 'json': this.buildMapClient = new JsonBuildMapClient(buildGroup, effectiveCfg); break
            case 'db2':  this.buildMapClient = new Db2BuildMapClient(buildGroup, effectiveCfg);  break
            case 'dbb':  this.buildMapClient = new DbbBuildMapClient(buildGroup, effectiveCfg);  break
            default: throw new IllegalArgumentException("Unknown buildMapClientType: '${this.buildMapClientType}'")
        }

        if (fileOpsType == 'zos') {
            this.fileOps = new JzosFileService()
        } else if (fileOpsType == 'uss') {
            if (uxBasedir == null)
                throw new IllegalArgumentException('uxBasedir must be defined when fileOpsType is set to uss')
            this.fileOps = new UssFileService(uxBasedir)
        } else if (fileOpsType == 'macos') {
            if (uxBasedir == null)
                throw new IllegalArgumentException('uxBasedir must be defined when fileOpsType is set to macos')
            this.fileOps = new MacosFileService(uxBasedir)
        } else {
            throw new IllegalArgumentException("Unknown fileOpsType '$fileOpsType'")
        }

        rules       = new DeletionRulesLoader().load(rulesFile)
        stageMap    = new StageMapLoader().load(stageMapFile)
        extractor   = new PathVariableExtractor()
        envChain    = new EnvironmentChain()
        deleteLogic = new DeleteCassaforteLogic(ops: fileOps, rules: rules, buildMap: buildMapClient)
        sfilamento  = new SfilamentoLogic(
            ops:            fileOps,
            deleteLogic:    deleteLogic,
            rules:          rules,
            envChain:       envChain,
            extractor:      extractor,
            stageMap:       stageMap,
            hlq:            hlq,
            jobzExtensions: jobzExtensions
        )

        log.info("Processing list='{}' env='{}' buildGroup='{}'",
                 listToProcess, environment, buildGroup)
        int processed = 0, errors = 0
        listToProcess.eachLine { raw ->
            def line = raw.trim()
            if (!line || line.startsWith('#')) return
            def comma = line.indexOf(',')
            if (comma < 0) {
                log.warn("Skipping malformed line: '{}'", line)
                errors++
                return
            }
            def action     = line.substring(0, comma).trim().toUpperCase()
            def sourcePath = line.substring(comma + 1).trim()
            def fileType   = resolveFileType(sourcePath)

            try {
                switch (action) {
                    case 'C':
                        def vars = isJobzType(fileType)
                            ? extractor.extractJobz(environment, stageMap, hlq, fileType)
                            : extractor.extract(sourcePath, environment, stageMap, hlq)
                        deleteLogic.execute(sourcePath, fileType, vars, buildGroup)
                        processed++
                        break
                    case 'S':
                        sfilamento.execute(sourcePath, fileType, environment, buildGroup)
                        processed++
                        break
                    default:
                        log.warn("Unknown action '{}' in line: '{}'", action, line)
                        errors++
                }
            } catch (Exception e) {
                log.error("ERROR processing '{}': {}", sourcePath, e.message, e)
                errors++
            }
        }

        log.info("PuliziaCassaforte: processed={} errors={}", processed, errors)
        return errors
    }

    int doPuliziaPostBuild(String sourceToProcess, String environment, String buildGroup, Properties props) {
        // This method processes one file at a time 
    }

    private boolean isJobzType(String fileType) {
        fileType?.trim() in jobzExtensions
    }

    private static String resolveFileType(String sourcePath) {
        def filename = sourcePath.tokenize('/').last()
        def ext = filename.contains('.') ? filename.substring(filename.lastIndexOf('.') + 1) : filename
        ext.toUpperCase().trim()
    }
}

// --- QueryBuildMapImpl.groovy ---
/**
 * Query build map using jar
 */
@Slf4j
class QueryBuildMapImpl {

    /**
     * Queries the build map for each source path in the list file against the live DBB metadata store.
     *
     * @param listFile      Path to the list file (one {@code <any>,<sourcePath>} per line).
     * @param buildGroup    DBB build group name.
     * @param userId        DB2 user ID.
     * @param pwFilePath    Path to the DB2 password file.
     * @param db2ConfigFile {@code db2Connection.conf} to use for the metadata store connection.
     * @return Number of errors encountered (0 = success).
     */
    int run(String listFile, String buildGroup,
            String userId, String pwFilePath, File db2ConfigFile) {
        BuildMapClient buildMap
        try {
            def cfg = new PuliziaCassaforteConfig(
                userId:        userId,
                pwFilePath:    pwFilePath,
                db2ConfigPath: db2ConfigFile.canonicalPath
            )
            buildMap = new Db2BuildMapClient(buildGroup, cfg)
        } catch (IllegalStateException e) {
            log.warn("build map unavailable: {} — build map lookups will return empty", e.message)
            System.exit(1)
        }
        return execute(listFile, buildGroup, buildMap)
    }

    /**
     * Queries the build map using a pre-captured JSON build map file (local / fallback).
     *
     * @param listFile   Path to the list file.
     * @param buildGroup DBB build group name.
     * @param bmFile     JSON build map file in {@link JsonBuildMapClient} format.
     * @return Number of errors encountered (0 = success).
     */
    int run(String listFile, String buildGroup, File bmFile) {
        def cfg = new PuliziaCassaforteConfig(buildMapPath: bmFile.canonicalPath)
        return execute(listFile, buildGroup, new JsonBuildMapClient(buildGroup, cfg))
    }

    /** Overload with explicit {@link BuildMapClient} — used by tests for injection. */
    int run(String listFile, String buildGroup, BuildMapClient buildMap) {
        return execute(listFile, buildGroup, buildMap)
    }

    private int execute(String listFile, String buildGroup, BuildMapClient buildMap) {
        int processed = 0, errors = 0
        new File(listFile).eachLine { raw ->
            def line = raw.trim()
            if (!line || line.startsWith('#')) return
            def comma = line.indexOf(',')
            if (comma < 0) {
                log.warn("Skipping malformed line: '{}'", line)
                errors++
                return
            }

            def sourcePath = line.substring(comma + 1).trim()
            log.info("Querying build map on '{}' for '{}'", buildGroup, sourcePath)

            try {
                buildMap.getGeneratedObjects(sourcePath).each { genObj ->
                    log.info("{} -> {}", sourcePath, genObj)
                }
                processed++
            } catch (Exception e) {
                log.error("ERROR processing '{}': {}", sourcePath, e.message, e)
                errors++
            }
        }

        log.info("QueryBuildMapImpl: processed={} errors={}", processed, errors)
        return errors
    }
}

// --- SfilamentoLogic.groovy ---
/**
 * Implements the sfilamento (S-action) scenario: delete the current environment's cassaforte
 * member and, if applicable, restore it from the nearest superior environment.
 *
 * <h3>When does sfilamento apply?</h3>
 * <ul>
 *   <li>Only in environment {@code ST} ({@link EnvironmentChain#supportsSfilamento}).</li>
 *   <li>Only for file types matching {@code SJCL*} (JCL source members).</li>
 * </ul>
 *
 * <h3>Restore logic</h3>
 * <p>After deleting the ST cassaforte member, the logic walks {@link EnvironmentChain#getSuperiors}
 * in order (e.g. {@code PR}) and, for each rule matching the file type, looks for the member in
 * that environment's cassaforte library.  The first copy found is restored into the ST
 * TOCOLB library (derived via {@link LibraryNameResolver#toTocolbLibrary}) and the loop stops.
 *
 * <p>Returns {@code true} if a restore was performed, {@code false} if no copy was found
 * or the file type is not sfilamento-eligible.
 *
 * @see DeleteCassaforteLogic
 * @see EnvironmentChain
 * @see LibraryNameResolver#toTocolbLibrary
 */
@Slf4j
class SfilamentoLogic {
    FileService           ops
    DeleteCassaforteLogic deleteLogic
    List<DeletionRule>    rules
    PathVariableExtractor extractor      = new PathVariableExtractor()
    Map<String, String>   stageMap       = [:]
    String                hlq            = ''
    PatternMatcher        matcher        = new PatternMatcher()
    LibraryNameResolver   resolver       = new LibraryNameResolver()
    EnvironmentChain      envChain       = new EnvironmentChain()
    Set<String>           jobzExtensions = [] as Set

    boolean execute(String sourcePath, String fileType, String environment, String buildGroup) {
        boolean isJobz = fileType?.trim() in jobzExtensions
        def currentVars = isJobz
            ? extractor.extractJobz(environment, stageMap, hlq, fileType)
            : extractor.extract(sourcePath, environment, stageMap, hlq)
        deleteLogic.execute(sourcePath, fileType, currentVars, buildGroup)

        boolean eligibleForRestore = isJobz || matcher.matches('SJCL*', fileType)
        if (!eligibleForRestore) {
            log.debug("Sfilamento skipped: fileType '{}' does not match SJCL* and is not jobz", fileType)
            return false
        }
        if (!envChain.supportsSfilamento(environment)) {
            // S reverts to C when the environment has no superior (terminal env like PR).
            // Returns true so the caller knows the deletion completed successfully.
            if (envChain.getSuperiors(environment).isEmpty()) {
                log.debug("Sfilamento degraded to C: environment '{}' has no superior", environment)
                return true
            }
            log.debug("Sfilamento skipped: environment '{}' does not support it", environment)
            return false
        }

        def member   = DeleteCassaforteLogic.memberName(sourcePath)
        def matching = rules.findAll { matcher.matches(it.typePattern, fileType) }

        for (String superEnv : envChain.getSuperiors(environment)) {
            log.debug("Sfilamento: checking in superior environment '{}'", superEnv)
            def superVars = isJobz
                ? extractor.extractJobz(superEnv, stageMap, hlq, fileType)
                : extractor.extract(sourcePath, superEnv, stageMap, hlq)
            for (def rule : matching) {
                def srcLib = resolver.resolve(rule.libraryTemplate, superVars)
                log.debug("Sfilamento: looking for '{}({})'", srcLib, member)
                def src    = "//${srcLib}(${member})"
                if (ops.exists(src)) {
                    def localLib = resolver.resolve(rule.libraryTemplate, currentVars)
                    def tocolb   = resolver.toTocolbLibrary(localLib)
                    def dst      = "//${tocolb}(${member})"
                    log.info("Sfilamento: restoring {} -> {}", src, dst)
                    ops.copy(src, dst)
                    return true
                }
            }
        }
        log.info("Sfilamento: no restore source found for member '{}' in superiors of '{}'",
                 member, environment)
        return false
    }
}

// --- StageMapLoader.groovy ---
/**
 * Loads the ISP stage-map CSV into a lookup map.
 *
 * <p>CSV format (semicolon-delimited, keys and values wrapped in double-quotes,
 * with optional leading whitespace per line):
 * <pre>
 *   "01|ATO";"X2A"
 * </pre>
 * Key format: {@code PATH_LO|BUILD_ENV} (e.g. {@code "01|ATO"}).
 * Value: C1STAGE code (e.g. {@code "X2A"}).
 */
@Slf4j
class StageMapLoader {

    Map<String, String> load(File file) {
        log.debug("Loading stage map from: {}", file.canonicalPath)
        def result = file.readLines()
            .findAll { it.trim() }
            .collectEntries { line ->
                def parts = line.trim().split(';', -1)
                if (parts.size() < 2)
                    throw new IllegalArgumentException("Malformed stagemap row: '$line'")
                def key   = parts[0].trim().replace('"', '')
                def value = parts[1].trim().replace('"', '')
                log.trace("Parsed stagemap entry: '{}' -> '{}'", key, value)
                [key, value]
            }
        log.info("Loaded {} stagemap entries from: {}", result.size(), file)
        result
    }
}

// --- UssFileService.groovy ---
/**
 * USS Unix-filesystem adapter of the {@link FileService} trait.
 *
 * <p>Simulates a z/OS PDS environment by mapping z/OS-style dataset paths onto ordinary
 * directories under a configurable {@code baseDir} (default: {@code /tmp/zos-sim/}):
 * <pre>
 *   //DATASET.NAME(MEMBER)  →  &lt;baseDir&gt;/DATASET.NAME/MEMBER   (PDS member = file)
 *   //DATASET.NAME          →  &lt;baseDir&gt;/DATASET.NAME           (PDS = directory)
 * </pre>
 *
 * <p>Only z/OS syntax (//DSN(MEMBER)) is supported. Unix paths are rejected with
 * {@link IllegalArgumentException}. Uses {@link java.nio.file.Files} for all I/O — no IBM/DBB dependencies.
 * Suitable for running on USS HFS/zFS without the IBM JZOS jar.
 *
 * @see FileService
 * @see JzosFileService
 */
@Slf4j
class UssFileService implements FileService {

    final String baseDir

    UssFileService(String baseDir = '/tmp/zos-sim') {
        this.baseDir = baseDir
        log.debug("UssFileService initialized with baseDir: {}", baseDir)
    }

    /**
     * Parses a z/OS path into [dsn, member].
     * Member is null if path has no (MEMBER) component.
     * //DSN(MEMBER) → ['DSN', 'MEMBER']
     * //DSN → ['DSN', null]
     * Non-z/OS paths throw IllegalArgumentException.
     */
    private List<String> parseDsnMember(String zosPath) {
        if (!zosPath.startsWith('//')) {
            throw new IllegalArgumentException("Path must use z/OS syntax (//DSN or //DSN(MEMBER)), got: ${zosPath}")
        }
        def inner = zosPath.substring(2)
        def m = (inner =~ /^(.+?)\((.+?)\)$/) // matches DATASET(MEMBER) pattern
        m.matches() ? [m.group(1), m.group(2)] : [inner, null]
    }

    private Path resolve(String dsn, String member) {
        member ? Paths.get(baseDir, dsn, member) : Paths.get(baseDir, dsn)
    }

    boolean exists(String path) {
        def (dsn, member) = parseDsnMember(path)
        if (!member) {
            throw new IllegalArgumentException("exists() requires a member reference (//DSN(MEMBER)), got: ${path}")
        }
        def result = Files.exists(resolve(dsn, member))
        log.debug("exists({}): {}", path, result)
        result
    }

    void delete(String path) {
        log.debug("delete({})", path)
        def (dsn, member) = parseDsnMember(path)
        if (!member) {
            throw new IllegalArgumentException("delete() requires a member reference (//DSN(MEMBER)), got: ${path}")
        }
        Files.deleteIfExists(resolve(dsn, member))
    }

    void copy(String src, String dst) {
        log.debug("copy({} -> {})", src, dst)
        def (srcDsn, srcMember) = parseDsnMember(src)
        def (dstDsn, dstMember) = parseDsnMember(dst)

        if (!srcMember || !dstMember) {
            throw new IllegalArgumentException("copy() requires member references (//DSN(MEMBER)), got: src=${src} dst=${dst}")
        }

        if (srcMember != dstMember) {
            log.warn("copy({} -> {}): source member '{}' differs from destination member '{}'", src, dst, srcMember, dstMember)
        }

        def dstPath = resolve(dstDsn, dstMember)
        Files.createDirectories(dstPath.parent)
        def srcPath = resolve(srcDsn, srcMember)
        if (Files.exists(srcPath)) {
            Files.copy(srcPath, dstPath, StandardCopyOption.REPLACE_EXISTING)
        } else {
            Files.createFile(dstPath) // src absent → create empty dst, simulating a z/OS member with no content
        }
    }

    List<String> list(String container) {
        def (dsn, member) = parseDsnMember(container)
        // list() accepts member but ignores it, using only DSN
        def dir = resolve(dsn, null)
        if (!Files.isDirectory(dir)) {
            log.debug("list({}): not a directory", container)
            return []
        }
        def result = dir.toFile().list()?.toList() ?: []
        log.debug("list({}): {} member(s)", container, result.size())
        result
    }

}

// --- ScriptLoaderHelper.groovy (script) ---
// This code is meaningful only for groovy scripts loaded via ScriptLoader.loadScript()
// from another script run in USS by groovyz
// It will be appended to the end of FullPuliziaCassaforte.groovy

def createPuliziaCassaforteImpl() {
    return PuliziaCassaforteImpl.newInstance()
}

