// ============================================================
// FAT SOURCE — auto-generated by merge_groovy.py
// Sources merged: 18 files from '/Users/bomitalievelino/Documents/Workspace/isp-ibm-mauden/repo/pulizia-cassaforte/library/src/main/groovy'
// ============================================================

import groovy.json.JsonSlurper
import groovy.util.logging.Slf4j
import java.nio.file.*
import java.util.regex.Pattern

// --- BuildMapClient.groovy ---
/**
 * Trait (interface) for querying the DBB build map to resolve generated output objects.
 *
 * <p>In the cassaforte deletion flow, when a {@link DeletionRule} has {@code useBuildMap = true},
 * the generated member name (which may differ from the source name) must be looked up before
 * the PDS entry can be deleted.  This trait decouples that lookup from the deletion logic.
 *
 * <p>Two implementations:
 * <ul>
 *   <li>{@link LocalBuildMapClient} — reads a pre-captured JSON fixture; used in unit tests.</li>
 *   <li>{@code ZosBuildMapClient}   — queries the live DBB build map on USS (not yet implemented).</li>
 * </ul>
 *
 * @see DeletionRule#useBuildMap
 * @see DeleteCassaforteLogic
 */
@Slf4j
trait BuildMapClient {
    abstract List<Map<String, String>> getGeneratedObjects(String sourcePath, String buildGroup)
}

// --- BuildMapClientFactory.groovy ---
/**
 * Factory for creating {@link BuildMapClient} instances without IBM/DBB compile-time dependencies.
 *
 * <p>Two creation paths:
 * <ul>
 *   <li>{@link #fromJson} — local dev / fallback; wraps {@link LocalBuildMapClient} over a
 *       pre-captured JSON build map file.</li>
 *   <li>{@link #fromConf} — USS production; delegates to {@code ZosBuildMapClient.fromConf()}
 *       (in the USS-only jar) via reflection.</li>
 * </ul>
 *
 * @see BuildMapClient
 * @see LocalBuildMapClient
 */
@Slf4j
class BuildMapClientFactory {

    /**
     * Creates a {@link BuildMapClient} backed by a pre-captured JSON build map file.
     *
     * @param bmFile JSON file in the {@link LocalBuildMapClient} array format.
     */
    static BuildMapClient fromJson(File bmFile) {
        log.debug("Creating local BuildMapClient from JSON: {}", bmFile)
        return new LocalBuildMapClient(bmFile.canonicalPath)
    }

    /**
     * Creates a {@link BuildMapClient} connected to the live DBB metadata store.
     *
     * <p>{@code ZosBuildMapClient} is resolved via reflection to avoid a compile-time
     * dependency on IBM jars — it must be on the classpath at runtime (USS only).
     *
     * @param buildGroupName DBB build group name.
     * @param userId         DB2 user ID.
     * @param pwFilePath     Path to the DB2 password file.
     * @param configFile     {@code db2Connection.conf} to use; defaults to
     *                       {@code ${DBB_CONF:-${DBB_HOME}/conf}/db2Connection.conf}.
     * @throws ClassNotFoundException  if {@code ZosBuildMapClient} is not on the classpath.
     * @throws IllegalStateException   if the build group is not found in the metadata store.
     */
    static BuildMapClient fromConf(String buildGroupName, String userId, String pwFilePath,
                                   File configFile = defaultConfigFile()) {
        log.info("Creating ZosBuildMapClient for group '{}' user '{}'", buildGroupName, userId)
        return Class.forName('ZosBuildMapClient')
                    .fromConf(configFile.parent, buildGroupName, userId, pwFilePath) as BuildMapClient
    }

    private static File defaultConfigFile() {
        String confDir = System.getenv('DBB_CONF') ?: "${System.getenv('DBB_HOME')}/conf"
        return new File(confDir, 'db2Connection.conf')
    }
}

// --- DeleteCassaforteLogic.groovy ---
/**
 * Core business logic for deleting members from cassaforte (staging) PDS libraries.
 *
 * <p>For each source file to process, the caller provides its path, resolved file type,
 * environment stage code, system identifier, and DBB build group.  This class:
 * <ol>
 *   <li>Filters the loaded {@link DeletionRule} list by matching the file type against
 *       each rule's {@code typePattern} via {@link PatternMatcher}.</li>
 *   <li>Resolves the target PDS name from the rule's {@code libraryTemplate} using
 *       {@link LibraryNameResolver}.</li>
 *   <li>Determines the PDS member name — either directly from the source filename, or
 *       by querying the {@link BuildMapClient} when {@code useBuildMap = true}.</li>
 *   <li>Calls {@link ZosFileOps#delete} on each matching member that exists.</li>
 * </ol>
 *
 * <p>This class has zero IBM/DBB imports; all environment interaction is injected
 * via the {@link ZosFileOps} and {@link BuildMapClient} traits.
 *
 * @see DeletionRule
 * @see SfilamentoLogic
 * @see PrevEnvCleanLogic
 */
@Slf4j
class DeleteCassaforteLogic {
    ZosFileOps          ops
    List<DeletionRule>  rules
    BuildMapClient      buildMap
    PatternMatcher      matcher  = new PatternMatcher()
    LibraryNameResolver resolver = new LibraryNameResolver()

    // vars map must contain C1STAGE, C1SYSTEM, HLQ — resolved by caller per source file.
    // Returns number of delete operations performed.
    int execute(String sourcePath, String fileType, Map<String,String> vars, String buildGroup) {
        def member   = memberName(sourcePath)
        def matching = rules.findAll { matcher.matches(it.typePattern, fileType) }
        log.debug("execute: sourcePath='{}' fileType='{}' buildGroup='{}' matchingRules={}",
                  sourcePath, fileType, buildGroup, matching.size())
        int count    = 0

        matching.each { rule ->
            def lib = resolver.resolve(rule.libraryTemplate, vars)
            if (rule.useBuildMap) {
                buildMap.getGeneratedObjects(sourcePath, buildGroup).each { obj ->
                    def zp = "//${lib}(${obj.member})"
                    if (ops.exists(zp)) {
                        log.info("Deleting (build-map): {}", zp)
                        ops.delete(zp)
                        count++
                    }
                }
            } else {
                def zp = "//${lib}(${member})"
                if (ops.exists(zp)) {
                    log.info("Deleting: {}", zp)
                    ops.delete(zp)
                    count++
                }
            }
        }
        log.debug("execute: {} deletion(s) performed for '{}'", count, sourcePath)
        count
    }

    static String memberName(String sourcePath) {
        def filename = sourcePath.tokenize('/').last()
        def name = filename.contains('.') ? filename.take(filename.lastIndexOf('.')) : filename
        name.toUpperCase()
    }
}

// --- DeletionRule.groovy ---
/**
 * Immutable value object representing one row from the deletion-rules CSV file.
 *
 * <p>Fields:
 * <ul>
 *   <li>{@code typePattern}     — member-type glob matched against the source file type
 *                                 ({@code %} = exactly one char, {@code *} = zero or more).</li>
 *   <li>{@code libraryTemplate} — parametric PDS name with {@code ${C1STAGE}} / {@code ${C1SYSTEM}}
 *                                 placeholders resolved at runtime by {@link LibraryNameResolver}.</li>
 *   <li>{@code useBuildMap}     — when {@code true}, the generated object name is resolved via the
 *                                 DBB build map instead of being derived directly from the source name.</li>
 * </ul>
 *
 * @see DeletionRulesLoader
 * @see PatternMatcher
 * @see LibraryNameResolver
 */
@groovy.util.logging.Slf4j
@groovy.transform.Immutable
class DeletionRule {
    String typePattern
    String libraryTemplate
    boolean useBuildMap
}

// --- DeletionRulesLoader.groovy ---
/**
 * Reads the deletion-rules CSV file and converts each non-blank, non-comment line
 * into a {@link DeletionRule} instance consumed by the cassaforte cleanup logic.
 *
 * <p>Expected CSV format (semicolon-separated, 3 fields):
 * <pre>
 *   &lt;type-pattern&gt;;&lt;parametric-library&gt;;&lt;flag&gt;
 * </pre>
 * <ul>
 *   <li>{@code type-pattern}   — member-type glob ({@code %} = one char, {@code *} = any chars)</li>
 *   <li>{@code parametric-library} — target PDS template, may contain {@code ${C1STAGE}} / {@code ${C1SYSTEM}}</li>
 *   <li>{@code flag}           — {@code NO} to delete by source name;
 *                                {@code BUILD MAP} to resolve the generated object name via DBB build map</li>
 * </ul>
 *
 * <p>Lines starting with {@code #} are treated as comments and skipped.
 *
 * @see DeletionRule
 * @see scripts/build-data/rules.csv
 */
@Slf4j
class DeletionRulesLoader {

    List<DeletionRule> load(File file) {
        log.debug("Loading deletion rules from: {}", file)
        def result = file.readLines()
            .findAll { it.trim() && !it.startsWith('#') }
            .collect { line ->
                def parts = line.split(';', -1)
                if (parts.size() < 3)
                    throw new IllegalArgumentException("Invalid rule (need 3 semicolon-separated fields): '$line'")
                new DeletionRule(
                    typePattern:     parts[0].trim(),
                    libraryTemplate: parts[1].trim(),
                    useBuildMap:     parts[2].trim() == 'BUILD MAP'
                )
            }
        log.info("Loaded {} deletion rules from: {}", result.size(), file)
        result
    }
}

// --- EnvironmentChain.groovy ---
/**
 * Models the ISP build pipeline's ordered environment chain and the relationships
 * between environments used by the cassaforte cleanup scripts.
 *
 * <h3>Environment chain</h3>
 * <pre>
 *   ATI → ATO → ST → PR
 *   EM  (standalone, no predecessor)
 * </pre>
 *
 * <h3>Stage codes (C1STAGE)</h3>
 * <pre>
 *   ATI → I1 | ATO → O1 | ST → S1 | PR → P1 | EM → E1
 * </pre>
 *
 * <h3>Key relationships</h3>
 * <ul>
 *   <li><b>Predecessor</b> ({@link #getPredecessor}): the environment immediately before in
 *       the chain; used by {@link PrevEnvCleanLogic} to delete stale cassaforte members
 *       after a successful build.</li>
 *   <li><b>Superiors</b> ({@link #getSuperiors}): environments further ahead in the chain
 *       that may hold a stable copy to restore from; used by {@link SfilamentoLogic}.</li>
 * </ul>
 *
 * <h3>Capability flags</h3>
 * <ul>
 *   <li>{@link #requiresPrevEnvClean} — true for ST and PR (they have a predecessor).</li>
 *   <li>{@link #supportsSfilamento}   — true only for ST (the SAD restore step).</li>
 * </ul>
 */
@Slf4j
class EnvironmentChain {

    static final Map<String, String> PREDECESSORS = [
        ST: 'ATO',
        PR: 'ST',
    ]

    static final Map<String, List<String>> SUPERIORS = [
        ST:  ['PR'],
        ATI: ['ATO'],
        ATO: ['ST'],
    ]

    // TODO: verify EM and SDD stage codes against actual ISP build configuration.
    static final Map<String, String> STAGE_BY_ENV = [
        ATI: 'I1',
        ATO: 'O1',
        ST:  'S1',
        PR:  'P1',
        EM:  'E1',
    ]

    String getPredecessor(String env) {
        PREDECESSORS[env?.toUpperCase()]
    }

    List<String> getSuperiors(String env) {
        SUPERIORS[env?.toUpperCase()] ?: []
    }

    String getStage(String env) {
        def stage = STAGE_BY_ENV[env?.toUpperCase()]
        if (!stage) {
            log.error("Unknown environment: '{}'", env)
            throw new IllegalArgumentException("Unknown environment: '${env ?: 'null'}'")
        }
        stage
    }

    boolean requiresPrevEnvClean(String env) {
        env?.toUpperCase() in PREDECESSORS.keySet()
    }

    boolean supportsSfilamento(String env) {
        env?.toUpperCase() == 'ST'
    }
}

// --- LibraryNameResolver.groovy ---
/**
 * Resolves parametric PDS library names by substituting ISP stage and system tokens,
 * and derives TOCOLB library names from cassaforte library names.
 *
 * <h3>Template substitution</h3>
 * <p>Library templates stored in the deletion-rules CSV may contain two placeholders:
 * <ul>
 *   <li>{@code ${C1STAGE}}  — the two-character stage code for the target environment
 *                             (e.g. {@code I1}, {@code O1}, {@code S1}, {@code P1}).</li>
 *   <li>{@code ${C1SYSTEM}} — the application system identifier (e.g. {@code YN}).</li>
 * </ul>
 *
 * <h3>TOCOLB derivation</h3>
 * <p>The sfilamento restore target (TOCOLB library) is computed by transforming qualifiers
 * 4 and 5 (1-based) of the resolved cassaforte library name:
 * <pre>
 *   qualifier 4: replaces the pattern {@code @@@@}     with {@code TO@@}
 *   qualifier 5: replaces the pattern {@code @@@@@@@@} with {@code COLB@@@@}
 * </pre>
 *
 * @see DeletionRule#libraryTemplate
 * @see SfilamentoLogic
 */
@Slf4j
class LibraryNameResolver {
    String resolve(String template, Map<String, String> vars) {
        def result = vars.inject(template) { acc, key, val ->
            acc.replace('${' + key + '}', val ?: '')
        }
        def unresolved = (result =~ /\$\{[^}]+\}/)
        if (unresolved) {
            log.error("Unresolved macro: {} in template: '{}'", unresolved[0], template)
            throw new IllegalStateException(
                "Unresolved macro: ${unresolved[0]} in template: '${template}'"
            )
        }
        log.debug("resolve: '{}' -> '{}'", template, result)
        result
    }

    // Derives TOCOLB library from resolved cassaforte library.
    // 4th qualifier '@@@@' → 'TO@@', 5th qualifier '@@@@@@@@' → 'COLB@@@@'.
    String toTocolbLibrary(String resolvedLibrary) {
        def parts = resolvedLibrary.split('\\.', -1)
        if (parts.size() >= 5) {
            parts[3] = parts[3].replace('@@@@', 'TO@@')
            parts[4] = parts[4].replace('@@@@@@@@', 'COLB@@@@')
        }
        def result = parts.join('.')
        log.debug("toTocolbLibrary: '{}' -> '{}'", resolvedLibrary, result)
        result
    }
}

// --- LocalBuildMapClient.groovy ---
/**
 * Local-filesystem implementation of {@link BuildMapClient} used during unit testing.
 *
 * <p>Reads a pre-captured DBB build-map JSON file (see {@code src/test/resources/fixtures/buildmap.json})
 * and returns the list of generated output objects for a given source path and build group.
 *
 * <p>The JSON file is an array of DBB build-map entries, each with {@code buildFile}, {@code group},
 * and {@code outputs} (list of {@code {member, dataset}} objects) — matching the structure of the
 * real DBB build map API response.  A single-object file is also accepted.
 *
 * <p>This class has no IBM/DBB dependencies and can run in any standard JVM.
 *
 * @see BuildMapClient
 * @see LocalFileOps
 */
@Slf4j
class LocalBuildMapClient implements BuildMapClient {
    private final List data

    LocalBuildMapClient(String jsonFilePath) {
        def parsed = new JsonSlurper().parse(new File(jsonFilePath))
        data = (parsed instanceof List) ? parsed : [parsed]
        log.debug("Loaded {} build map entries from: {}", data.size(), jsonFilePath)
    }

    List<Map<String, String>> getGeneratedObjects(String sourcePath, String buildGroup) {
        def entry = data.find { it.buildFile == sourcePath && it.group == buildGroup }
        if (!entry) {
            log.debug("getGeneratedObjects: no entry for '{}' in group '{}'", sourcePath, buildGroup)
            return []
        }
        def result = ((entry.outputs ?: []) as List)
            .findAll { it.dataset && it.member }
            .collect { [library: it.dataset as String, member: it.member as String] }
        log.debug("getGeneratedObjects: '{}' group '{}' -> {} object(s)", sourcePath, buildGroup, result.size())
        result
    }
}

// --- LocalFileOps.groovy ---
/**
 * Local-filesystem adapter of the {@link ZosFileOps} trait used during unit testing.
 *
 * <p>Simulates a z/OS PDS environment by mapping z/OS-style dataset paths onto ordinary
 * directories under a configurable {@code baseDir} (default: {@code /tmp/zos-sim/}):
 * <pre>
 *   //DATASET.NAME(MEMBER)  →  &lt;baseDir&gt;/DATASET.NAME/MEMBER   (PDS member = file)
 *   //DATASET.NAME          →  &lt;baseDir&gt;/DATASET.NAME           (PDS = directory)
 *   /path/to/file           →  /path/to/file                     (USS path, passed through)
 * </pre>
 *
 * <p>Uses {@link java.nio.file.Files} for all I/O — no IBM/DBB dependencies.
 * Tests inject a JUnit 5 {@code @TempDir} as {@code baseDir} for full isolation.
 *
 * @see ZosFileOps
 * @see ZosFileOpsUSS
 */
@Slf4j
class LocalFileOps implements ZosFileOps {

    final String baseDir

    LocalFileOps(String baseDir = '/tmp/zos-sim') {
        this.baseDir = baseDir
        log.debug("LocalFileOps initialized with baseDir: {}", baseDir)
    }

    // Translates a z/OS-style path to a local filesystem path under baseDir.
    // PDS member //HLQ.DS(MEMBER) → <baseDir>/HLQ.DS/MEMBER; plain //HLQ.DS → <baseDir>/HLQ.DS; USS path passed through.
    private Path resolve(String zosPath) {
        if (zosPath.startsWith('//')) {
            def inner = zosPath.substring(2)
            def m = (inner =~ /^(.+?)\((.+?)\)$/) // matches DATASET(MEMBER) pattern
            if (m.matches()) return Paths.get(baseDir, m.group(1), m.group(2))
            return Paths.get(baseDir, inner)
        }
        Paths.get(zosPath)
    }

    boolean exists(String path) {
        def result = Files.exists(resolve(path))
        log.debug("exists({}): {}", path, result)
        result
    }

    void delete(String path) {
        log.debug("delete({})", path)
        Files.deleteIfExists(resolve(path))
    }

    void copy(String src, String dst) {
        log.debug("copy({} -> {})", src, dst)
        def dstPath = resolve(dst)
        Files.createDirectories(dstPath.parent)
        def srcPath = resolve(src)
        if (Files.exists(srcPath)) {
            Files.copy(srcPath, dstPath, StandardCopyOption.REPLACE_EXISTING)
        } else {
            Files.createFile(dstPath) // src absent → create empty dst, simulating a z/OS member with no content
        }
    }

    List<String> list(String container) {
        def dir = resolve(container)
        if (!Files.isDirectory(dir)) {
            log.debug("list({}): not a directory", container)
            return []
        }
        def result = dir.toFile().list()?.toList() ?: []
        log.debug("list({}): {} member(s)", container, result.size())
        result
    }

}

// --- PathVariableExtractor.groovy ---
/**
 * Extracts per-file template variables from a source path.
 *
 * <p>Identifies the application segment in the path (the component whose
 * underscore-delimited tokens satisfy {@code tokens[2] =~ /\d+/}), then
 * looks up the C1STAGE in the stage map using {@code PATH_LO|buildEnv}.
 *
 * <p>Returns a map with keys {@code C1STAGE}, {@code C1SYSTEM}, {@code HLQ}.
 *
 * @see StageMapLoader
 * @see LibraryNameResolver
 */
@Slf4j
class PathVariableExtractor {

    // Jobz paths have no application segment; layer operativo is always '01' and C1SYSTEM is not applicable.
    Map<String, String> extractJobz(String buildEnv, Map<String, String> stageMap, String hlq) {
        def key = "01|${buildEnv}"
        def c1stage = stageMap[key]
        if (!c1stage)
            throw new IllegalArgumentException(
                "No stage-map entry for '${key}' (jobz path, env='${buildEnv}')"
            )
        def result = [C1STAGE: c1stage, C1SYSTEM: '', HLQ: hlq ?: '']
        log.debug("extractJobz: env='{}' -> C1STAGE='{}' HLQ='{}'", buildEnv, c1stage, hlq)
        result
    }

    Map<String, String> extract(String sourcePath, String buildEnv,
                                Map<String, String> stageMap, String hlq) {
        def segment = sourcePath.tokenize('/').find { part ->
            def tokens = part.split('_')
            tokens.size() >= 5 && tokens[2] ==~ /\d+/
        }
        if (!segment)
            throw new IllegalArgumentException(
                "No application segment found in source path: '${sourcePath}'"
            )

        def tokens   = segment.split('_')
        def c1system = tokens[1]
        def pathLo   = tokens[2]
        def key      = "${pathLo}|${buildEnv}"
        def c1stage  = stageMap[key]
        if (!c1stage)
            throw new IllegalArgumentException(
                "No stage-map entry for '${key}' (path: '${sourcePath}')"
            )

        def result = [C1STAGE: c1stage, C1SYSTEM: c1system, HLQ: hlq ?: '']
        log.debug("extract: path='{}' env='{}' -> C1STAGE='{}' C1SYSTEM='{}' HLQ='{}'",
                  sourcePath, buildEnv, c1stage, c1system, hlq)
        result
    }
}

// --- PatternMatcher.groovy ---
/**
 * Converts z/OS-style glob patterns to regular expressions and tests whether a value matches.
 *
 * <p>Supported wildcards (aligned with the ISP deletion-rules convention):
 * <ul>
 *   <li>{@code %} — matches exactly one character (equivalent to regex {@code .}).</li>
 *   <li>{@code *} — matches zero or more characters (equivalent to regex {@code .*}).</li>
 * </ul>
 *
 * All other characters are treated as literals.
 *
 * <p>Example: pattern {@code SJCL*} matches {@code SJCL}, {@code SJCLLOAD}, {@code SJCL123},
 * while {@code S%CL} matches only four-character strings starting with S and ending with CL.
 *
 * @see DeletionRule#typePattern
 */
@Slf4j
class PatternMatcher {
    boolean matches(String pattern, String value) {
        def regex = pattern.trim().collect { c ->
            switch (c) {
                case '%': return '.'
                case '*': return '.*'
                default:  return Pattern.quote(String.valueOf(c))
            }
        }.join('')
        def result = value.trim() ==~ regex
        log.trace("matches('{}', '{}') = {}", pattern, value, result)
        result
    }
}

// --- PrevEnvCleanLogic.groovy ---
/**
 * DBB post-build task logic: deletes the corresponding cassaforte member from the
 * <em>predecessor</em> environment after a successful compile step.
 *
 * <h3>Purpose</h3>
 * <p>When a source is promoted from environment N-1 to N, the N-1 cassaforte library
 * may still contain a stale copy of the old object.  If the N-1 library participates in
 * a concatenation with N, the stale entry shadows the new one.  This logic removes it
 * so that the concatenation always resolves to the most recently promoted version.
 *
 * <h3>Applicability</h3>
 * <p>Runs only in environments that have a predecessor
 * ({@link EnvironmentChain#requiresPrevEnvClean}): currently {@code ST} and {@code PR}.
 * Returns 0 immediately for all other environments (ATI, ATO, EM).
 *
 * @see DeleteCassaforteLogic
 * @see EnvironmentChain#requiresPrevEnvClean
 * @see EnvironmentChain#getPredecessor
 */
@Slf4j
class PrevEnvCleanLogic {
    DeleteCassaforteLogic deleteLogic
    PathVariableExtractor extractor  = new PathVariableExtractor()
    Map<String, String>   stageMap   = [:]
    String                hlq        = ''
    EnvironmentChain      envChain   = new EnvironmentChain()

    int execute(String sourcePath, String fileType, String environment, String buildGroup) {
        if (!envChain.requiresPrevEnvClean(environment)) {
            log.debug("Skipping prevEnvClean for environment '{}' (no predecessor)", environment)
            return 0
        }
        def prevEnv  = envChain.getPredecessor(environment)
        log.info("Cleaning predecessor '{}' cassaforte for sourcePath='{}'", prevEnv, sourcePath)
        def prevVars = extractor.extract(sourcePath, prevEnv, stageMap, hlq)
        deleteLogic.execute(sourcePath, fileType, prevVars, buildGroup)
    }
}

// --- PuliziaCassaforteImpl.groovy ---
/**
 * Business logic for the {@code PuliziaCassaforte.groovy} entry point.
 *
 * <p>Compiled into {@code pulizia-cassaforte.jar} so it is available on both USS
 * (via {@code groovyz}) and local dev (via {@code groovy}).  Has no IBM/DBB compile-time
 * dependencies — IBM types are accessed via reflection where needed.
 *
 * @see DeleteCassaforteLogic
 * @see SfilamentoLogic
 */
@Slf4j
class PuliziaCassaforteImpl {

    String fileOpsType   = 'zos' // set value to 'local' to use LocalFileOps for file operations, which is useful for testing
    String buildMapClientType = 'db2' // set value to 'json' to read build map from JSON file instead of DB2, which is useful for testing

    // Used by db2 build map client
    String userId        = null
    String pwFilePath    = null
    String db2ConfigPath = null

    // Used by JSON build map client
    String buildMapPath  = null

    // Used by LocalFileOps if fileOpsType is set to 'local'
    String uxBasedir     = null

    // Used by ZosFileOps if fileOpsType is set to 'zos'
    String hlq           = null

    Set<String> jobzExtensions = [] as Set

    // Default paths to rules and stage map CSVs. Override in tests or when running on USS.
    String rulesPath    = 'build-data/rules.csv'
    File   rulesFile    = null
    String stageMapPath = 'build-data/stage-map.csv'
    File   stageMapFile = null

    BuildMapClient buildMapClient = null
    ZosFileOps fileOps = null

    List rules                    = null
    Map stageMap                  = null
    PathVariableExtractor extractor = null
    EnvironmentChain envChain     = null
    DeleteCassaforteLogic deleteLogic = null
    SfilamentoLogic sfilamento    = null

    int run(String listFileToProcess, String environment, String buildGroup, String configFile = 'PuliziaCassaforte.properties') {
        Properties props = new Properties()
        new File(configFile).withInputStream { props.load(it) }
        return run(listFileToProcess, environment, buildGroup, props)
    }

    int run(String listFileToProcess, String environment, String buildGroup, Properties props) {
        log.info("Starting PuliziaCassaforte")
        if (props.getProperty('fileOpsType'))        this.fileOpsType        = props.getProperty('fileOpsType')
        if (props.getProperty('buildMapClientType')) this.buildMapClientType = props.getProperty('buildMapClientType')
        if (props.getProperty('rulesPath'))     this.rulesPath     = props.getProperty('rulesPath')
        if (props.getProperty('stageMapPath'))  this.stageMapPath  = props.getProperty('stageMapPath')
        if (props.getProperty('uxBasedir'))     this.uxBasedir     = props.getProperty('uxBasedir')
        if (props.getProperty('hlq'))           this.hlq           = props.getProperty('hlq')
        if (props.getProperty('userId'))        this.userId        = props.getProperty('userId')
        if (props.getProperty('pwFilePath'))    this.pwFilePath    = props.getProperty('pwFilePath')
        if (props.getProperty('db2ConfigPath')) this.db2ConfigPath = props.getProperty('db2ConfigPath')
        if (props.getProperty('buildMapPath'))  this.buildMapPath  = props.getProperty('buildMapPath')
        if (props.getProperty('jobzExtensions')) {
            this.jobzExtensions = props.getProperty('jobzExtensions')
                .split(',').collect { it.trim().toUpperCase() }.findAll { it }.toSet()
        }

        if (!listFileToProcess)
            throw new IllegalArgumentException('listFileToProcess argument is required')
        File lftp = new File(listFileToProcess)
        if (!lftp.exists()) {
            throw new IllegalArgumentException("listFileToProcess file not found: '$listFileToProcess'")
        }
        if (!rulesPath || !stageMapPath)
            throw new IllegalArgumentException('rulesPath and stageMapPath must be defined in config')
        rulesFile    = new File(rulesPath)
        stageMapFile = new File(stageMapPath)
        if (!rulesFile.exists())
            throw new IllegalArgumentException("rulesPath file not found: '$rulesPath'")
        if (!stageMapFile.exists())
            throw new IllegalArgumentException("stageMapPath file not found: '$stageMapPath'")

        if (buildMapClientType == 'db2') {
            int credCount = [userId, pwFilePath, db2ConfigPath].count { it != null }
            if (credCount == 0)
                throw new IllegalArgumentException('config must define userId (db2) or buildMapPath (json)')
            if (credCount < 3)
                throw new IllegalArgumentException('userId, pwFilePath and db2ConfigPath must all be defined or none')
            this.buildMapClient = BuildMapClientFactory.fromConf(buildGroup, userId, pwFilePath, new File(db2ConfigPath))
        } else if (buildMapClientType == 'json') {
            this.buildMapClient = BuildMapClientFactory.fromJson(new File(buildMapPath))
        } else {
            throw new IllegalArgumentException('config must define userId or buildMapPath')
        }

        if (fileOpsType == 'zos') {
            this.fileOps = ZosFileOpsFactory.createOnZos()
        } else if (fileOpsType == 'local') {
            if (uxBasedir == null)
                throw new IllegalArgumentException('uxBasedir must be defined when fileOpsType is set to local')
            this.fileOps = new LocalFileOps(uxBasedir)
        } else {
            throw new IllegalArgumentException("Unknown fileOpsType '$fileOpsType'")
        }

        rules       = new DeletionRulesLoader().load(rulesFile)
        stageMap    = new StageMapLoader().load(stageMapFile)
        extractor   = new PathVariableExtractor()
        envChain    = new EnvironmentChain()
        deleteLogic = new DeleteCassaforteLogic(ops: fileOps, rules: rules, buildMap: buildMapClient)
        sfilamento  = new SfilamentoLogic(
            ops:            fileOps,
            deleteLogic:    deleteLogic,
            rules:          rules,
            envChain:       envChain,
            extractor:      extractor,
            stageMap:       stageMap,
            hlq:            hlq,
            jobzExtensions: jobzExtensions
        )

        log.info("Processing list='{}' env='{}' buildGroup='{}'",
                 listFileToProcess, environment, buildGroup)
        int processed = 0, errors = 0
        lftp.eachLine { raw ->
            def line = raw.trim()
            if (!line || line.startsWith('#')) return
            def comma = line.indexOf(',')
            if (comma < 0) {
                log.warn("Skipping malformed line: '{}'", line)
                errors++
                return
            }
            def action     = line.substring(0, comma).trim().toUpperCase()
            def sourcePath = line.substring(comma + 1).trim()
            def fileType   = resolveFileType(sourcePath)

            try {
                switch (action) {
                    case 'C':
                        def vars = isJobzType(fileType)
                            ? extractor.extractJobz(environment, stageMap, hlq)
                            : extractor.extract(sourcePath, environment, stageMap, hlq)
                        deleteLogic.execute(sourcePath, fileType, vars, buildGroup)
                        processed++
                        break
                    case 'S':
                        sfilamento.execute(sourcePath, fileType, environment, buildGroup)
                        processed++
                        break
                    default:
                        log.warn("Unknown action '{}' in line: '{}'", action, line)
                        errors++
                }
            } catch (Exception e) {
                log.error("ERROR processing '{}': {}", sourcePath, e.message, e)
                errors++
            }
        }

        log.info("PuliziaCassaforte: processed={} errors={}", processed, errors)
        return errors
    }

    private boolean isJobzType(String fileType) {
        fileType?.trim() in jobzExtensions
    }

    private static String resolveFileType(String sourcePath) {
        def filename = sourcePath.tokenize('/').last()
        def ext = filename.contains('.') ? filename.substring(filename.lastIndexOf('.') + 1) : filename
        ext.toUpperCase().trim()
    }
}

// --- QueryBuildMapImpl.groovy ---
/**
 * Query build map using jar
 */
@Slf4j
class QueryBuildMapImpl {

    /**
     * Queries the build map for each source path in the list file against the live DBB metadata store.
     *
     * @param listFile      Path to the list file (one {@code <any>,<sourcePath>} per line).
     * @param buildGroup    DBB build group name.
     * @param userId        DB2 user ID.
     * @param pwFilePath    Path to the DB2 password file.
     * @param db2ConfigFile {@code db2Connection.conf} to use for the metadata store connection.
     * @return Number of errors encountered (0 = success).
     */
    int run(String listFile, String buildGroup,
            String userId, String pwFilePath, File db2ConfigFile) {
        BuildMapClient buildMap
        try {
            buildMap = BuildMapClientFactory.fromConf(buildGroup, userId, pwFilePath, db2ConfigFile)
        } catch (IllegalStateException e) {
            log.warn("build map unavailable: {} — build map lookups will return empty", e.message)
            System.exit(1)
        }
        return execute(listFile, buildGroup, buildMap)
    }

    /**
     * Queries the build map using a pre-captured JSON build map file (local / fallback).
     *
     * @param listFile   Path to the list file.
     * @param buildGroup DBB build group name.
     * @param bmFile     JSON build map file in {@link LocalBuildMapClient} format.
     * @return Number of errors encountered (0 = success).
     */
    int run(String listFile, String buildGroup, File bmFile) {
        return execute(listFile, buildGroup, BuildMapClientFactory.fromJson(bmFile))
    }

    /** Overload with explicit {@link BuildMapClient} — used by tests for injection. */
    int run(String listFile, String buildGroup, BuildMapClient buildMap) {
        return execute(listFile, buildGroup, buildMap)
    }

    private int execute(String listFile, String buildGroup, BuildMapClient buildMap) {
        int processed = 0, errors = 0
        new File(listFile).eachLine { raw ->
            def line = raw.trim()
            if (!line || line.startsWith('#')) return
            def comma = line.indexOf(',')
            if (comma < 0) {
                log.warn("Skipping malformed line: '{}'", line)
                errors++
                return
            }

            def sourcePath = line.substring(comma + 1).trim()
            log.info("Querying build map on '{}' for '{}'", buildGroup, sourcePath)

            try {
                buildMap.getGeneratedObjects(sourcePath, buildGroup).each { genObj ->
                    log.info("{} -> {}", sourcePath, genObj)
                }
                processed++
            } catch (Exception e) {
                log.error("ERROR processing '{}': {}", sourcePath, e.message, e)
                errors++
            }
        }

        log.info("QueryBuildMapImpl: processed={} errors={}", processed, errors)
        return errors
    }
}

// --- SfilamentoLogic.groovy ---
/**
 * Implements the sfilamento (S-action) scenario: delete the current environment's cassaforte
 * member and, if applicable, restore it from the nearest superior environment.
 *
 * <h3>When does sfilamento apply?</h3>
 * <ul>
 *   <li>Only in environment {@code ST} ({@link EnvironmentChain#supportsSfilamento}).</li>
 *   <li>Only for file types matching {@code SJCL*} (JCL source members).</li>
 * </ul>
 *
 * <h3>Restore logic</h3>
 * <p>After deleting the ST cassaforte member, the logic walks {@link EnvironmentChain#getSuperiors}
 * in order (e.g. {@code PR}) and, for each rule matching the file type, looks for the member in
 * that environment's cassaforte library.  The first copy found is restored into the ST
 * TOCOLB library (derived via {@link LibraryNameResolver#toTocolbLibrary}) and the loop stops.
 *
 * <p>Returns {@code true} if a restore was performed, {@code false} if no copy was found
 * or the file type is not sfilamento-eligible.
 *
 * @see DeleteCassaforteLogic
 * @see EnvironmentChain
 * @see LibraryNameResolver#toTocolbLibrary
 */
@Slf4j
class SfilamentoLogic {
    ZosFileOps            ops
    DeleteCassaforteLogic deleteLogic
    List<DeletionRule>    rules
    PathVariableExtractor extractor      = new PathVariableExtractor()
    Map<String, String>   stageMap       = [:]
    String                hlq            = ''
    PatternMatcher        matcher        = new PatternMatcher()
    LibraryNameResolver   resolver       = new LibraryNameResolver()
    EnvironmentChain      envChain       = new EnvironmentChain()
    Set<String>           jobzExtensions = [] as Set

    boolean execute(String sourcePath, String fileType, String environment, String buildGroup) {
        boolean isJobz = fileType?.trim() in jobzExtensions
        def currentVars = isJobz
            ? extractor.extractJobz(environment, stageMap, hlq)
            : extractor.extract(sourcePath, environment, stageMap, hlq)
        deleteLogic.execute(sourcePath, fileType, currentVars, buildGroup)

        boolean eligibleForRestore = isJobz || matcher.matches('SJCL*', fileType)
        if (!eligibleForRestore) {
            log.debug("Sfilamento skipped: fileType '{}' does not match SJCL* and is not jobz", fileType)
            return false
        }
        if (!envChain.supportsSfilamento(environment)) {
            log.debug("Sfilamento skipped: environment '{}' does not support it", environment)
            return false
        }

        def member   = DeleteCassaforteLogic.memberName(sourcePath)
        def matching = rules.findAll { matcher.matches(it.typePattern, fileType) }
        log.info("Sfilamento: searching restore for member '{}' fileType '{}' in environment '{}'",
                 member, fileType, environment)

        for (String superEnv : envChain.getSuperiors(environment)) {
            def superVars = isJobz
                ? extractor.extractJobz(superEnv, stageMap, hlq)
                : extractor.extract(sourcePath, superEnv, stageMap, hlq)
            for (def rule : matching) {
                def srcLib = resolver.resolve(rule.libraryTemplate, superVars)
                def src    = "//${srcLib}(${member})"
                if (ops.exists(src)) {
                    def localLib = resolver.resolve(rule.libraryTemplate, currentVars)
                    def tocolb   = resolver.toTocolbLibrary(localLib)
                    def dst      = "//${tocolb}(${member})"
                    log.info("Sfilamento: restoring {} -> {}", src, dst)
                    ops.copy(src, dst)
                    return true
                }
            }
        }
        log.info("Sfilamento: no restore source found for member '{}' in superiors of '{}'",
                 member, environment)
        return false
    }
}

// --- StageMapLoader.groovy ---
/**
 * Loads the ISP stage-map CSV into a lookup map.
 *
 * <p>CSV format (semicolon-delimited, keys and values wrapped in double-quotes,
 * with optional leading whitespace per line):
 * <pre>
 *   "01|ATO";"X2A"
 * </pre>
 * Key format: {@code PATH_LO|BUILD_ENV} (e.g. {@code "01|ATO"}).
 * Value: C1STAGE code (e.g. {@code "X2A"}).
 */
@Slf4j
class StageMapLoader {

    Map<String, String> load(File file) {
        log.debug("Loading stage map from: {}", file)
        def result = file.readLines()
            .findAll { it.trim() }
            .collectEntries { line ->
                def parts = line.trim().split(';', -1)
                if (parts.size() < 2)
                    throw new IllegalArgumentException("Malformed stagemap row: '$line'")
                def key   = parts[0].trim().replace('"', '')
                def value = parts[1].trim().replace('"', '')
                [key, value]
            }
        log.info("Loaded {} stagemap entries from: {}", result.size(), file)
        result
    }
}

// --- ZosFileOps.groovy ---
/**
 * Trait (interface) that abstracts z/OS file operations consumed by the cassaforte cleanup logic.
 *
 * <p>Two implementations are provided:
 * <ul>
 *   <li>{@link LocalFileOps}    — maps z/OS-style paths onto the local filesystem for unit testing.</li>
 *   <li>{@code ZosFileOpsUSS}   — delegates to IBM JZOS {@code ZFile} on z/OS USS (packaged separately).</li>
 * </ul>
 *
 * <p>Path convention used by all implementations:
 * <pre>
 *   //DATASET.NAME(MEMBER)  — PDS/PDSE member
 *   //DATASET.NAME          — sequential dataset or PDS root
 *   /path/to/file           — USS HFS/zFS path (passed through unchanged)
 * </pre>
 */
@Slf4j
trait ZosFileOps {

    abstract boolean exists(String path)
    abstract void    delete(String path)
    abstract void    copy(String src, String dst)
    abstract List<String> list(String container)

}

// --- ZosFileOpsFactory.groovy ---
/**
 * Factory for creating {@link ZosFileOps} instances without IBM/DBB compile-time dependencies.
 *
 * <p>On USS (with {@code ZosFileOpsUSS} on the classpath) returns a live USS implementation;
 * falls back to {@link LocalFileOps} for local dev.
 *
 * @see ZosFileOps
 * @see LocalFileOps
 */
@Slf4j
class ZosFileOpsFactory {

    /** Returns {@code ZosFileOpsUSS} on USS, {@link LocalFileOps} otherwise. */
    static ZosFileOps create() {
        try {
            def impl = createOnZos()
            log.info("Using ZosFileOpsUSS")
            return impl
        } catch (ClassNotFoundException ignored) {
            log.info("ZosFileOpsUSS not found on classpath — using LocalFileOps")
            return mockZos()
        }
    }

    /**
     * Loads and returns a {@code ZosFileOpsUSS} instance via reflection.
     *
     * @throws ClassNotFoundException if {@code ZosFileOpsUSS} is not on the classpath.
     */
    static ZosFileOps createOnZos() {
        log.debug("Loading ZosFileOpsUSS via reflection")
        return Class.forName('ZosFileOpsUSS').newInstance() as ZosFileOps
    }

    /** Returns a {@link LocalFileOps} instance for local testing without z/OS dependencies. */
    static ZosFileOps mockZos() {
        log.debug("Creating LocalFileOps for local testing")
        return new LocalFileOps()
    }
}

