// ============================================================
// FAT SOURCE — auto-generated by merge_groovy.py
// Sources merged: 4 files from '/Users/bomitalievelino/Documents/Workspace/isp-ibm-mauden/repo/pulizia-cassaforte-main/jzos/build/temp-filesources'
// ============================================================

import com.ibm.jzos.ZFile
import com.ibm.jzos.ZFileException
import groovy.util.logging.Slf4j
import java.nio.file.*

// --- FileService.groovy ---
/**
 * Trait (interface) that abstracts z/OS file operations consumed by the cassaforte cleanup logic.
 *
 * <p>Two implementations are provided:
 * <ul>
 *   <li>{@link LocalFileOps}    — maps z/OS-style paths onto the local filesystem for unit testing.</li>
 *   <li>{@link JzosFileService}  — delegates to IBM JZOS {@code ZFile} on z/OS USS (packaged separately).</li>
 * </ul>
 *
 * <p>Path convention used by all implementations:
 * <pre>
 *   //DATASET.NAME(MEMBER)  — PDS/PDSE member
 *   //DATASET.NAME          — sequential dataset or PDS root
 *   /path/to/file           — USS HFS/zFS path (passed through unchanged)
 * </pre>
 */
@Slf4j
trait FileService {

    abstract boolean exists(String path)
    abstract void    delete(String path)
    abstract void    copy(String src, String dst)
    abstract List<String> list(String container)

}

// --- JzosFileService.groovy ---
// Mainframe-only. Must be compiled and run with groovyz on z/OS USS.
// After upload to USS: chtag -tc IBM-1047 JzosFileService.groovy
// ZFile javadoc https://www.ibm.com/docs/en/sdk-java-technology/8?topic=jzos-zfile

/**
 * z/OS USS implementation of the {@link FileService} trait.
 *
 * Provides file-system operations (exists, delete, copy, list) that transparently
 * target either MVS datasets or USS HFS/zFS paths depending on the path prefix:
 *
 *   //DATASET.NAME          — sequential dataset or PDS without member
 *   //DATASET.NAME(MEMBER)  — PDS/PDSE member
 *   /u/path/to/file         — USS HFS/zFS file or directory (any path not starting with //)
 *
 * The // prefix convention mirrors the JCL DSN= notation used by IBM tools.
 * This class delegates MVS operations to the IBM JZOS {@link ZFile} API and
 * USS operations to standard {@link java.io.File}.
 *
 * Compiled against JZOS stubs (compileOnly) so it builds locally without IBM jars.
 * At runtime on z/OS USS the real JZOS classes must be on the classpath.
 */
@Slf4j
class JzosFileService implements FileService {

    /**
     * Checks whether a dataset, PDS member, or USS path exists.
     *
     * For MVS PDS members (//DSN(MBR)): lists PDS directory and checks membership.
     * For MVS datasets (//DSN): queries the system catalog via {@link ZFile#dsExists(String)}.
     * For USS paths: delegates to {@link java.io.File#exists()}.
     *
     * @param path  MVS dataset reference (// prefix) or USS absolute path.
     * @return true if the dataset, member, or file is found.
     */
    boolean exists(String path) {
        if (path.startsWith('//')) {
            def (dsn, member) = parseDsn(path)
            boolean result
            if (member) {
                // dsExists is catalog-level only; open the member to confirm it exists
                try {
                    def zf = new ZFile("//'${dsn}(${member})'", 'rb,type=record')
                    zf.close()
                    result = true
                } catch (ZFileException ignored) {
                    result = false
                }
            } else {
                result = ZFile.dsExists(dsn)
            }
            log.debug("exists({}): {}", path, result)
            return result
        }
        def result = new File(path).exists()
        log.debug("exists({}): {}", path, result)
        result
    }

    /**
     * Deletes a dataset member, a sequential dataset, or a USS file.
     *
     * For MVS PDS members: pre-allocates the PDS with SHR disposition and deletes via
     * {@code //DD:} reference to avoid exclusive lock contention that can cause
     * ZFile.remove() to fail with EDC5091I errors when the dataset is in use.
     * For sequential datasets: allocates with SHR and deletes via DD reference for consistency.
     * For USS paths: delegates to {@link java.io.File#delete()}.
     *
     * <p>Pre-allocation pattern: ZFile.remove() normally takes an exclusive (OLD) allocation,
     * which fails if the dataset/member is in use. By pre-allocating with SHR and using
     * {@code //DD:ddname} reference, LE's C runtime reuses the SHR allocation instead.
     * See docs/zfile_remove.md for architectural details.
     *
     * @param path  MVS dataset reference (// prefix) or USS absolute path.
     * @throws ZFileException if the MVS remove fails (e.g. dataset in use, not found).
     */
    void delete(String path) {
        log.debug("delete({})", path)
        if (path.startsWith('//')) {
            def (dsn, member) = parseDsn(path)
            String ddname = 'DELDD'
            String spec = member ? "${dsn}(${member})" : dsn
            try {
                // Allocate the dataset with SHR to avoid exclusive lock contention
                ZFile.bpxwdyn("alloc fi(${ddname}) da('${dsn}') shr msg(2)")
                // Delete via //DD: reference so LE reuses the SHR allocation
                ZFile.remove("//DD:${ddname}${member ? '(' + member + ')' : ''}")
            } finally {
                // Always free the allocation
                try {
                    ZFile.bpxwdyn("free fi(${ddname})")
                } catch (ZFileException e) {
                    log.warn("Failed to free DD ${ddname}: {}", e.message)
                }
            }
            return
        }
        new File(path).delete()
    }

    /**
     * Copies a dataset (or member) to another dataset (or member), or copies a USS file.
     *
     * MVS-to-MVS copy: opens source with {@code rb,type=record} and destination with
     * {@code wb,type=record} so that logical z/OS records are preserved exactly.
     * Reads and writes in chunks of 32760 bytes — the maximum LRECL for RECFM=VB records
     * on z/OS (0x7FF8). Both files are closed in finally blocks to avoid dataset locks
     * even if an exception occurs mid-transfer.
     *
     * USS copy: reads all bytes from src and writes them to dst atomically via Groovy's
     * {@link java.io.File#setBytes(byte[])} assignment — suitable for small USS files.
     *
     * Mixed USS→MVS or MVS→USS is not supported; both paths must be of the same type.
     *
     * @param src  Source: MVS dataset reference (// prefix) or USS path.
     * @param dst  Destination: MVS dataset reference (// prefix) or USS path.
     * @throws ZFileException if the MVS open, read, or write fails.
     */
    void copy(String src, String dst) {
        log.debug("copy({} -> {})", src, dst)
        if (src.startsWith('//') && dst.startsWith('//')) {
            def (srcDsn, srcMember) = parseDsn(src)
            def (dstDsn, dstMember) = parseDsn(dst)
            def srcSpec = srcMember ? "${srcDsn}(${srcMember})" : srcDsn
            def dstSpec = dstMember ? "${dstDsn}(${dstMember})" : dstDsn
            // rb/wb with type=record: ZFile reads/writes complete logical records,
            // preserving RECFM and blocking without EBCDIC↔ASCII translation
            def srcFile = new ZFile("//'${srcSpec}'", 'rb,type=record')
            try {
                def dstFile = new ZFile("//'${dstSpec}'", 'wb,type=record')
                try {
                    // 32760 = max VB block payload (0x7FF8); safe upper bound for any LRECL
                    def buf = new byte[32760]
                    int len
                    while ((len = srcFile.read(buf)) >= 0) {
                        dstFile.write(buf, 0, len)
                    }
                } finally {
                    dstFile.close()
                }
            } finally {
                srcFile.close()
            }
            return
        }
        // USS file copy
        new File(dst).bytes = new File(src).bytes
    }

    /**
     * Lists members of a PDS/PDSE or files in a USS directory.
     *
     * For MVS paths: calls {@link ZFile#listMembers(String)} which returns the directory
     * entries of the PDS/PDSE identified by the dataset name (member component ignored).
     * For USS paths: delegates to {@link java.io.File#list()} for directory entries.
     *
     * @param container  MVS PDS/PDSE reference (// prefix) or USS directory path.
     * @return list of member or file names; empty list if the container is empty or null.
     */
    List<String> list(String container) {
        if (container.startsWith('//')) {
            // listMembers returns null if the PDS has no members — coerce to empty list
            def result = ZFile.listMembers(mvsName(container))?.toList() ?: []
            log.debug("list({}): {} member(s)", container, result.size())
            return result
        }
        def result = new File(container).list()?.toList() ?: []
        log.debug("list({}): {} entry(s)", container, result.size())
        result
    }

    // ─── private helpers ──────────────────────────────────────────────────────

    /**
     * Extracts the dataset name from an MVS path, discarding any member component.
     * Used for catalog-level operations (exists) where only the DSN is needed.
     *
     * Examples:
     *   //MY.DATASET          → MY.DATASET
     *   //MY.DATASET(MEMBER)  → MY.DATASET
     *
     * @param path  MVS path with // prefix.
     * @return dataset name without member.
     */
    private String mvsName(String path) {
        def inner = path.substring(2)
        def m = (inner =~ /^(.+?)\((.+?)\)$/)
        m.matches() ? m.group(1) : inner
    }

    /**
     * Parses an MVS path into a [dsn, member] pair.
     * Returns [dsn, null] when no member component is present.
     *
     * Examples:
     *   //MY.DATASET          → ['MY.DATASET', null]
     *   //MY.DATASET(MEMBER)  → ['MY.DATASET', 'MEMBER']
     *
     * @param path  MVS path with // prefix.
     * @return two-element list [datasetName, memberName]; memberName is null if absent.
     */
    private List<String> parseDsn(String path) {
        def inner = path.substring(2)
        def m = (inner =~ /^(.+?)\((.+?)\)$/)
        m.matches() ? [m.group(1), m.group(2)] : [inner, null]
    }
}

// --- MacosFileService.groovy ---
/**
 * macOS/local-dev adapter of the {@link FileService} trait used during unit testing.
 *
 * <p>Simulates a z/OS PDS environment by mapping z/OS-style dataset paths onto ordinary
 * directories under a configurable {@code baseDir} (default: {@code /tmp/zos-sim/}):
 * <pre>
 *   //DATASET.NAME(MEMBER)  →  &lt;baseDir&gt;/DATASET.NAME/MEMBER   (PDS member = file)
 *   //DATASET.NAME          →  &lt;baseDir&gt;/DATASET.NAME           (PDS = directory)
 *   /path/to/file           →  /path/to/file                     (USS path, passed through)
 * </pre>
 *
 * <p>Uses {@link java.nio.file.Files} for all I/O — no IBM/DBB dependencies.
 * Tests inject a JUnit 5 {@code @TempDir} as {@code baseDir} for full isolation.
 *
 * @see FileService
 * @see UssFileService
 * @see JzosFileService
 */
@Slf4j
class MacosFileService implements FileService {

    final String baseDir

    MacosFileService(String baseDir = '/tmp/zos-sim') {
        this.baseDir = baseDir
        log.debug("MacosFileService initialized with baseDir: {}", baseDir)
    }

    // Translates a z/OS-style path to a local filesystem path under baseDir.
    // PDS member //HLQ.DS(MEMBER) → <baseDir>/HLQ.DS/MEMBER; plain //HLQ.DS → <baseDir>/HLQ.DS; USS path passed through.
    private Path resolve(String zosPath) {
        if (zosPath.startsWith('//')) {
            def inner = zosPath.substring(2)
            def m = (inner =~ /^(.+?)\((.+?)\)$/) // matches DATASET(MEMBER) pattern
            if (m.matches()) return Paths.get(baseDir, m.group(1), m.group(2))
            return Paths.get(baseDir, inner)
        }
        Paths.get(zosPath)
    }

    boolean exists(String path) {
        def result = Files.exists(resolve(path))
        log.debug("exists({}): {}", path, result)
        result
    }

    void delete(String path) {
        log.debug("delete({})", path)
        Files.deleteIfExists(resolve(path))
    }

    void copy(String src, String dst) {
        log.debug("copy({} -> {})", src, dst)
        def dstPath = resolve(dst)
        Files.createDirectories(dstPath.parent)
        def srcPath = resolve(src)
        if (Files.exists(srcPath)) {
            Files.copy(srcPath, dstPath, StandardCopyOption.REPLACE_EXISTING)
        } else {
            Files.createFile(dstPath) // src absent → create empty dst, simulating a z/OS member with no content
        }
    }

    List<String> list(String container) {
        def dir = resolve(container)
        if (!Files.isDirectory(dir)) {
            log.debug("list({}): not a directory", container)
            return []
        }
        def result = dir.toFile().list()?.toList() ?: []
        log.debug("list({}): {} member(s)", container, result.size())
        result
    }

}

// --- UssFileService.groovy ---
/**
 * USS Unix-filesystem adapter of the {@link FileService} trait.
 *
 * <p>Simulates a z/OS PDS environment by mapping z/OS-style dataset paths onto ordinary
 * directories under a configurable {@code baseDir} (default: {@code /tmp/zos-sim/}):
 * <pre>
 *   //DATASET.NAME(MEMBER)  →  &lt;baseDir&gt;/DATASET.NAME/MEMBER   (PDS member = file)
 *   //DATASET.NAME          →  &lt;baseDir&gt;/DATASET.NAME           (PDS = directory)
 *   /path/to/file           →  /path/to/file                     (USS path, passed through)
 * </pre>
 *
 * <p>Uses {@link java.nio.file.Files} for all I/O — no IBM/DBB dependencies.
 * Suitable for running on USS HFS/zFS without the IBM JZOS jar.
 *
 * @see FileService
 * @see JzosFileService
 */
@Slf4j
class UssFileService implements FileService {

    final String baseDir

    UssFileService(String baseDir = '/tmp/zos-sim') {
        this.baseDir = baseDir
        log.debug("UssFileService initialized with baseDir: {}", baseDir)
    }

    // Translates a z/OS-style path to a local filesystem path under baseDir.
    // PDS member //HLQ.DS(MEMBER) → <baseDir>/HLQ.DS/MEMBER; plain //HLQ.DS → <baseDir>/HLQ.DS; USS path passed through.
    private Path resolve(String zosPath) {
        if (zosPath.startsWith('//')) {
            def inner = zosPath.substring(2)
            def m = (inner =~ /^(.+?)\((.+?)\)$/) // matches DATASET(MEMBER) pattern
            if (m.matches()) return Paths.get(baseDir, m.group(1), m.group(2))
            return Paths.get(baseDir, inner)
        }
        Paths.get(zosPath)
    }

    boolean exists(String path) {
        def result = Files.exists(resolve(path))
        log.debug("exists({}): {}", path, result)
        result
    }

    void delete(String path) {
        log.debug("delete({})", path)
        Files.deleteIfExists(resolve(path))
    }

    void copy(String src, String dst) {
        log.debug("copy({} -> {})", src, dst)
        def dstPath = resolve(dst)
        Files.createDirectories(dstPath.parent)
        def srcPath = resolve(src)
        if (Files.exists(srcPath)) {
            Files.copy(srcPath, dstPath, StandardCopyOption.REPLACE_EXISTING)
        } else {
            Files.createFile(dstPath) // src absent → create empty dst, simulating a z/OS member with no content
        }
    }

    List<String> list(String container) {
        def dir = resolve(container)
        if (!Files.isDirectory(dir)) {
            log.debug("list({}): not a directory", container)
            return []
        }
        def result = dir.toFile().list()?.toList() ?: []
        log.debug("list({}): {} member(s)", container, result.size())
        result
    }

}

