// ============================================================
// FAT SOURCE — auto-generated by merge_groovy.py
// Sources merged: 4 files from '/Users/bomitalievelino/Documents/Workspace/isp-ibm-mauden/repo/pulizia-cassaforte-main/jzos/build/temp-filesources'
// ============================================================

import com.ibm.jzos.PdsDirectory
import com.ibm.jzos.PdsDirectory.MemberInfo
import com.ibm.jzos.ZFile
import com.ibm.jzos.ZFileException
import groovy.util.logging.Slf4j
import java.nio.file.*
import java.util.concurrent.atomic.AtomicInteger

// --- FileService.groovy ---
/**
 * Trait (interface) that abstracts z/OS PDS member operations for cassaforte cleanup logic.
 *
 * <p>Operates only on PDS/PDSE members. Dataset-level operations (allocation, deletion of entire datasets)
 * are out of scope. Unix/USS filesystem paths are not supported; all paths must use z/OS syntax.
 *
 * <p>Path format (required):
 * <pre>
 *   //DATASET.NAME(MEMBER)  — PDS/PDSE member (required; no plain dataset or Unix path references)
 * </pre>
 *
 * <p>Three implementations provided:
 * <ul>
 *   <li>{@link MacosFileService}  — simulates z/OS PDS on local filesystem for unit testing (macOS/Linux).</li>
 *   <li>{@link UssFileService}    — simulates z/OS PDS on USS filesystem (z/OS).</li>
 *   <li>{@link JzosFileService}   — delegates to IBM JZOS {@code ZFile} and {@code PdsDirectory} on z/OS USS.</li>
 * </ul>
 *
 * All operations require a member component and will throw {@link IllegalArgumentException} on
 * dataset-only or non-z/OS path references.
 */
@Slf4j
trait FileService {

    // all member only
    abstract boolean exists(String path)
    abstract void    delete(String path)
    abstract void    copy(String src, String dst)
    abstract List<String> list(String dsn)
}

// --- JzosFileService.groovy ---
// Mainframe-only. Must be compiled and run with groovyz on z/OS USS.
// After upload to USS: chtag -tc IBM-1047 JzosFileService.groovy
// ZFile javadoc https://www.ibm.com/docs/en/sdk-java-technology/8?topic=jzos-zfile


/**
 * z/OS PDS/PDSE member operations, implementing the member-only {@link FileService} trait.
 *
 * Every operation acts on a partitioned dataset member. References use the form:
 *
 *   //DSN(MEMBER)   or   DSN(MEMBER)     — a single member (exists / delete / copy)
 *   //DSN           or   DSN             — the library itself (list)
 *
 * A leading {@code //} is optional and stripped; the dataset name is always treated as
 * fully qualified (no userid prefix is added). exists / delete / copy reject a reference
 * without a member component, since this service does not perform dataset-level operations.
 *
 * Disposition: every path here is either a directory read or a member STOW, so DISP=SHR is
 * always the correct choice.
 *   - exists / list / copy-source  -> input open => SHR implicitly.
 *   - delete / copy-target         -> the library is pre-allocated SHR and the member is
 *                                     driven through a //DD: reference, so LE reuses the SHR
 *                                     allocation instead of taking its default exclusive
 *                                     (OLD) lock. STOW serializes the directory update.
 *
 * Compiled against JZOS stubs (compileOnly) so it builds locally without IBM jars.
 * At runtime on z/OS USS the real JZOS classes must be on the classpath.
 */
@Slf4j
class JzosFileService implements FileService {

    /** 32760 = max payload of a RECFM=VB block (0x7FF8); safe upper bound for any LRECL. */
    private static final int MAX_RECORD = 32760

    /** Per-JVM counter for unique DD names; avoids S99ERROR 0x410 on concurrent/retried ops. */
    private static final AtomicInteger DD_SEQ = new AtomicInteger()

    /**
     * True if {@code MEMBER} exists in the PDS named by {@code path} (//DSN(MEMBER)).
     *
     * Uses {@link ZFile#exists(String)}, which for a member reference reads the PDS
     * directory (input open => SHR). No exclusive allocation is taken.
     */
    boolean exists(String path) {
        def (dsn, member) = parse(path)
        requireMember(member, 'exists', path)
        boolean result
        try {
            result = ZFile.exists("//'${dsn}(${member})'")
        } catch (ZFileException ignored) {
            // Older JZOS levels could throw instead of returning false (APAR PM64118).
            result = false
        }
        log.debug('exists({}): {}', path, result)
        return result
    }

    /**
     * Deletes {@code MEMBER} from the PDS named by {@code path} (//DSN(MEMBER)).
     *
     * A member delete is a STOW DELETE on the directory, performed under DISP=SHR via a
     * //DD: reference so the whole library is not locked.
     */
    void delete(String path) {
        log.debug('delete({})', path)
        def (dsn, member) = parse(path)
        requireMember(member, 'delete', path)
        withShrDd(dsn) { String dd ->
            ZFile.remove("//DD:${dd}(${member})")
        }
    }

    /**
     * Copies a member from one PDS to another (or to a different member of the same PDS).
     * Both {@code src} and {@code dst} must be member references.
     *
     * Records are copied one logical record at a time with rb/wb + type=record, preserving
     * RECFM and record boundaries with no EBCDIC<->ASCII translation. The source opens for
     * input (SHR); the target member is written through a SHR-allocated //DD: reference, so
     * the target library is not exclusively locked. Both libraries must already exist and be
     * attribute-compatible.
     */
    void copy(String src, String dst) {
        log.debug('copy({} -> {})', src, dst)
        def (srcDsn, srcMember) = parse(src)
        def (dstDsn, dstMember) = parse(dst)
        requireMember(srcMember, 'copy(source)', src)
        requireMember(dstMember, 'copy(target)', dst)

        ZFile srcFile = new ZFile("//'${srcDsn}(${srcMember})'", 'rb,type=record')
        try {
            withShrDd(dstDsn) { String dd ->
                writeRecords(srcFile, "//DD:${dd}(${dstMember})")
            }
        } finally {
            srcFile.close()
        }
    }

    /**
     * Lists the members of the PDS/PDSE named by {@code dsn}, equivalent to
     * {@code tsocmd "LISTDS '<dsn>' MEMBERS"}. A leading {@code //} and any accidental
     * member component are tolerated and ignored. Members come back in directory order
     * (ascending by name), which is the order LISTDS reports; aliases are included.
     *
     * The directory is read with an input open (SHR). A sequential dataset, or a name that
     * cannot be opened as a directory, yields a clear IllegalArgumentException.
     */
    List<String> list(String dsn) {
        String lib = parse(dsn)[0]
        def members = []
        PdsDirectory dir
        try {
            dir = new PdsDirectory("//'${lib}'")   // input open => SHR
        } catch (ZFileException e) {
            throw new IllegalArgumentException(
                    "Cannot list '${lib}': not a partitioned dataset, or not found", e)
        }
        try {
            for (MemberInfo mi : dir) {
                members << mi.getName()             // mi.isAlias() available if filtering is wanted
            }
        } finally {
            dir.close()
        }
        log.debug('list({}): {} member(s)', dsn, members.size())
        return members
    }

    // ─── private helpers ──────────────────────────────────────────────────────

    /**
     * Allocates {@code dsn} with DISP=SHR to a unique DD, runs {@code body} with that DD
     * name, and unconditionally frees the DD afterwards. The unique DD name prevents the
     * S99ERROR 0x410 ("ddname already allocated") that a hardcoded name would cause on
     * concurrent or retried operations. A failure to free is logged, never propagated, so
     * it cannot mask the real outcome of {@code body}.
     */
    private void withShrDd(String dsn, Closure body) {
        String dd = uniqueDd()
        ZFile.bpxwdyn("alloc fi(${dd}) da('${dsn}') shr msg(2)")
        try {
            body.call(dd)
        } finally {
            try {
                ZFile.bpxwdyn("free fi(${dd})")
            } catch (Exception e) {
                log.warn('Failed to free DD {}: {}', dd, e.message)
            }
        }
    }

    /** Copies all logical records from an already-open source into {@code dstSpec}. */
    private void writeRecords(ZFile srcFile, String dstSpec) {
        ZFile dstFile = new ZFile(dstSpec, 'wb,type=record')
        try {
            byte[] buf = new byte[MAX_RECORD]
            int len
            // read() returns one record's length, or -1 at EOF; 0 is a valid empty record.
            while ((len = srcFile.read(buf)) >= 0) {
                dstFile.write(buf, 0, len)
            }
        } finally {
            dstFile.close()
        }
    }

    /** DD name "DDnnnnnn" (8 chars, leading alpha, hex suffix — all valid DD characters). */
    private String uniqueDd() {
        String.format('DD%06X', DD_SEQ.incrementAndGet() & 0xFFFFFF)
    }

    /**
     * Parses a reference into [dsn, member]; member is null when absent. A leading {@code //}
     * is optional.
     *   //MY.PDS(MBR)  -> ['MY.PDS', 'MBR']
     *   MY.PDS(MBR)    -> ['MY.PDS', 'MBR']
     *   //MY.PDS       -> ['MY.PDS', null]
     */
    private List<String> parse(String ref) {
        String s = ref.startsWith('//') ? ref.substring(2) : ref
        def m = (s =~ /^(.+?)\((.+?)\)$/)
        m.matches() ? [m.group(1), m.group(2)] : [s, null]
    }

    /** Enforces the member-only contract for exists / delete / copy. */
    private void requireMember(String member, String op, String ref) {
        if (!member) {
            throw new IllegalArgumentException(
                    "${op} requires a PDS member reference like //DSN(MEMBER), got: ${ref}")
        }
    }
}

// --- MacosFileService.groovy ---
/**
 * macOS/local-dev adapter of the {@link FileService} trait used during unit testing.
 *
 * <p>Simulates a z/OS PDS environment by mapping z/OS-style dataset paths onto ordinary
 * directories under a configurable {@code baseDir} (default: {@code /tmp/zos-sim/}):
 * <pre>
 *   //DATASET.NAME(MEMBER)  →  &lt;baseDir&gt;/DATASET.NAME/MEMBER   (PDS member = file)
 *   //DATASET.NAME          →  &lt;baseDir&gt;/DATASET.NAME           (PDS = directory)
 * </pre>
 *
 * <p>Only z/OS syntax (//DSN(MEMBER)) is supported. Unix paths are rejected with
 * {@link IllegalArgumentException}. Uses {@link java.nio.file.Files} for all I/O — no IBM/DBB dependencies.
 * Tests inject a JUnit 5 {@code @TempDir} as {@code baseDir} for full isolation.
 *
 * @see FileService
 * @see UssFileService
 * @see JzosFileService
 */
@Slf4j
class MacosFileService implements FileService {

    final String baseDir

    MacosFileService(String baseDir = '/tmp/zos-sim') {
        this.baseDir = baseDir
        log.debug("MacosFileService initialized with baseDir: {}", baseDir)
    }

    /**
     * Parses a z/OS path into [dsn, member].
     * Member is null if path has no (MEMBER) component.
     * //DSN(MEMBER) → ['DSN', 'MEMBER']
     * //DSN → ['DSN', null]
     * Non-z/OS paths throw IllegalArgumentException.
     */
    private List<String> parseDsnMember(String zosPath) {
        if (!zosPath.startsWith('//')) {
            throw new IllegalArgumentException("Path must use z/OS syntax (//DSN or //DSN(MEMBER)), got: ${zosPath}")
        }
        def inner = zosPath.substring(2)
        def m = (inner =~ /^(.+?)\((.+?)\)$/) // matches DATASET(MEMBER) pattern
        m.matches() ? [m.group(1), m.group(2)] : [inner, null]
    }

    private Path resolve(String dsn, String member) {
        member ? Paths.get(baseDir, dsn, member) : Paths.get(baseDir, dsn)
    }

    boolean exists(String path) {
        def (dsn, member) = parseDsnMember(path)
        if (!member) {
            throw new IllegalArgumentException("exists() requires a member reference (//DSN(MEMBER)), got: ${path}")
        }
        def result = Files.exists(resolve(dsn, member))
        log.debug("exists({}): {}", path, result)
        result
    }

    void delete(String path) {
        log.debug("delete({})", path)
        def (dsn, member) = parseDsnMember(path)
        if (!member) {
            throw new IllegalArgumentException("delete() requires a member reference (//DSN(MEMBER)), got: ${path}")
        }
        Files.deleteIfExists(resolve(dsn, member))
    }

    void copy(String src, String dst) {
        log.debug("copy({} -> {})", src, dst)
        def (srcDsn, srcMember) = parseDsnMember(src)
        def (dstDsn, dstMember) = parseDsnMember(dst)

        if (!srcMember || !dstMember) {
            throw new IllegalArgumentException("copy() requires member references (//DSN(MEMBER)), got: src=${src} dst=${dst}")
        }

        if (srcMember != dstMember) {
            log.warn("copy({} -> {}): source member '{}' differs from destination member '{}'", src, dst, srcMember, dstMember)
        }

        def dstPath = resolve(dstDsn, dstMember)
        Files.createDirectories(dstPath.parent)
        def srcPath = resolve(srcDsn, srcMember)
        if (Files.exists(srcPath)) {
            Files.copy(srcPath, dstPath, StandardCopyOption.REPLACE_EXISTING)
        } else {
            Files.createFile(dstPath) // src absent → create empty dst, simulating a z/OS member with no content
        }
    }

    List<String> list(String container) {
        def (dsn, member) = parseDsnMember(container)
        // list() accepts member but ignores it, using only DSN
        def dir = resolve(dsn, null)
        if (!Files.isDirectory(dir)) {
            log.debug("list({}): not a directory", container)
            return []
        }
        def result = dir.toFile().list()?.toList() ?: []
        log.debug("list({}): {} member(s)", container, result.size())
        result
    }

}

// --- UssFileService.groovy ---
/**
 * USS Unix-filesystem adapter of the {@link FileService} trait.
 *
 * <p>Simulates a z/OS PDS environment by mapping z/OS-style dataset paths onto ordinary
 * directories under a configurable {@code baseDir} (default: {@code /tmp/zos-sim/}):
 * <pre>
 *   //DATASET.NAME(MEMBER)  →  &lt;baseDir&gt;/DATASET.NAME/MEMBER   (PDS member = file)
 *   //DATASET.NAME          →  &lt;baseDir&gt;/DATASET.NAME           (PDS = directory)
 * </pre>
 *
 * <p>Only z/OS syntax (//DSN(MEMBER)) is supported. Unix paths are rejected with
 * {@link IllegalArgumentException}. Uses {@link java.nio.file.Files} for all I/O — no IBM/DBB dependencies.
 * Suitable for running on USS HFS/zFS without the IBM JZOS jar.
 *
 * @see FileService
 * @see JzosFileService
 */
@Slf4j
class UssFileService implements FileService {

    final String baseDir

    UssFileService(String baseDir = '/tmp/zos-sim') {
        this.baseDir = baseDir
        log.debug("UssFileService initialized with baseDir: {}", baseDir)
    }

    /**
     * Parses a z/OS path into [dsn, member].
     * Member is null if path has no (MEMBER) component.
     * //DSN(MEMBER) → ['DSN', 'MEMBER']
     * //DSN → ['DSN', null]
     * Non-z/OS paths throw IllegalArgumentException.
     */
    private List<String> parseDsnMember(String zosPath) {
        if (!zosPath.startsWith('//')) {
            throw new IllegalArgumentException("Path must use z/OS syntax (//DSN or //DSN(MEMBER)), got: ${zosPath}")
        }
        def inner = zosPath.substring(2)
        def m = (inner =~ /^(.+?)\((.+?)\)$/) // matches DATASET(MEMBER) pattern
        m.matches() ? [m.group(1), m.group(2)] : [inner, null]
    }

    private Path resolve(String dsn, String member) {
        member ? Paths.get(baseDir, dsn, member) : Paths.get(baseDir, dsn)
    }

    boolean exists(String path) {
        def (dsn, member) = parseDsnMember(path)
        if (!member) {
            throw new IllegalArgumentException("exists() requires a member reference (//DSN(MEMBER)), got: ${path}")
        }
        def result = Files.exists(resolve(dsn, member))
        log.debug("exists({}): {}", path, result)
        result
    }

    void delete(String path) {
        log.debug("delete({})", path)
        def (dsn, member) = parseDsnMember(path)
        if (!member) {
            throw new IllegalArgumentException("delete() requires a member reference (//DSN(MEMBER)), got: ${path}")
        }
        Files.deleteIfExists(resolve(dsn, member))
    }

    void copy(String src, String dst) {
        log.debug("copy({} -> {})", src, dst)
        def (srcDsn, srcMember) = parseDsnMember(src)
        def (dstDsn, dstMember) = parseDsnMember(dst)

        if (!srcMember || !dstMember) {
            throw new IllegalArgumentException("copy() requires member references (//DSN(MEMBER)), got: src=${src} dst=${dst}")
        }

        if (srcMember != dstMember) {
            log.warn("copy({} -> {}): source member '{}' differs from destination member '{}'", src, dst, srcMember, dstMember)
        }

        def dstPath = resolve(dstDsn, dstMember)
        Files.createDirectories(dstPath.parent)
        def srcPath = resolve(srcDsn, srcMember)
        if (Files.exists(srcPath)) {
            Files.copy(srcPath, dstPath, StandardCopyOption.REPLACE_EXISTING)
        } else {
            Files.createFile(dstPath) // src absent → create empty dst, simulating a z/OS member with no content
        }
    }

    List<String> list(String container) {
        def (dsn, member) = parseDsnMember(container)
        // list() accepts member but ignores it, using only DSN
        def dir = resolve(dsn, null)
        if (!Files.isDirectory(dir)) {
            log.debug("list({}): not a directory", container)
            return []
        }
        def result = dir.toFile().list()?.toList() ?: []
        log.debug("list({}): {} member(s)", container, result.size())
        result
    }

}

