#!/usr/bin/env python3
"""
merge_groovy.py — Merge multiple Groovy source files into a single fat source file.

Usage:
    python merge_groovy.py <src_dir> [output_file]

Arguments:
    src_dir      Directory containing .groovy source files (searched recursively)
    output_file  Output file path (default: fat_source.groovy)

Features:
    - Extracts and deduplicates package declarations (warns if mixed)
    - Merges and deduplicates import statements
    - Strips per-file package/import lines from class bodies
    - Appends all class/interface/enum/trait definitions in order
    - Groovy script files (no top-level class) are appended last
"""

import os
import re
import sys
from pathlib import Path


PACKAGE_RE   = re.compile(r'^\s*package\s+([\w.]+)\s*$', re.MULTILINE)
IMPORT_RE    = re.compile(r'^\s*import\s+(?:static\s+)?[\w.*]+\s*$', re.MULTILINE)
CLASS_DEF_RE = re.compile(
    r'^\s*(?:(?:public|protected|private|abstract|final|static)\s+)*'
    r'(?:class|interface|enum|trait|record)\s+\w+',
    re.MULTILINE
)


def strip_package_and_imports(source: str) -> str:
    """Remove package declaration and all import lines from a source string."""
    lines = source.splitlines(keepends=True)
    result = []
    for line in lines:
        if PACKAGE_RE.match(line.rstrip()):
            continue
        if IMPORT_RE.match(line.rstrip()):
            continue
        result.append(line)
    # Remove leading blank lines left after stripping
    text = ''.join(result).lstrip('\n')
    return text


def parse_file(path: Path):
    """Parse a single .groovy file, returning (package, imports[], body, is_script)."""
    source = path.read_text(encoding='utf-8')

    packages = PACKAGE_RE.findall(source)
    package  = packages[0] if packages else None

    imports  = [line.strip() for line in IMPORT_RE.findall(source)]

    body        = strip_package_and_imports(source)
    is_script   = not CLASS_DEF_RE.search(body)

    return package, imports, body, is_script


def merge(src_dir: str, output_file: str):
    src_path = Path(src_dir)
    groovy_files = sorted(src_path.rglob('*.groovy'))

    if not groovy_files:
        print(f"No .groovy files found in {src_dir}", file=sys.stderr)
        sys.exit(1)

    all_packages = set()
    all_imports  = []
    seen_imports = set()
    class_bodies = []   # (filename, body)
    script_bodies = []  # (filename, body)

    for f in groovy_files:
        print(f"  Processing: {f.relative_to(src_path)}")
        pkg, imports, body, is_script = parse_file(f)

        if pkg:
            all_packages.add(pkg)

        for imp in imports:
            if imp not in seen_imports:
                seen_imports.add(imp)
                all_imports.append(imp)

        if is_script:
            script_bodies.append((f.name, body))
        else:
            class_bodies.append((f.name, body))

    # Warn if multiple packages found
    if len(all_packages) > 1:
        print(f"\n⚠️  WARNING: multiple packages found: {all_packages}", file=sys.stderr)
        print("   All classes will be placed under the first one found.", file=sys.stderr)
        print("   Review the output and fix package declarations manually if needed.\n",
              file=sys.stderr)

    # Build output
    lines = []

    # Header comment
    lines.append("// ============================================================")
    lines.append("// FAT SOURCE — auto-generated by merge_groovy.py")
    lines.append(f"// Sources merged: {len(groovy_files)} files from '{src_dir}'")
    lines.append("// ============================================================")
    lines.append("")

    # Package declaration
    if all_packages:
        pkg = sorted(all_packages)[0]
        lines.append(f"package {pkg}")
        lines.append("")

    # Imports
    if all_imports:
        # Group: static imports first, then regular
        static_imp  = sorted(i for i in all_imports if i.startswith('import static'))
        regular_imp = sorted(i for i in all_imports if not i.startswith('import static'))
        for imp in static_imp + regular_imp:
            lines.append(imp)
        lines.append("")

    # Class bodies
    for fname, body in class_bodies:
        lines.append(f"// --- {fname} ---")
        lines.append(body.rstrip())
        lines.append("")

    # Script bodies (last)
    for fname, body in script_bodies:
        lines.append(f"// --- {fname} (script) ---")
        lines.append(body.rstrip())
        lines.append("")

    output = '\n'.join(lines) + '\n'

    out_path = Path(output_file)
    out_path.write_text(output, encoding='utf-8')

    print(f"\n✅ Fat source written to: {out_path}")
    print(f"   Classes : {len(class_bodies)}")
    print(f"   Scripts : {len(script_bodies)}")
    print(f"   Imports : {len(all_imports)}")
    if all_packages:
        print(f"   Package : {sorted(all_packages)[0]}")


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    src_dir     = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else 'fat_source.groovy'
    merge(src_dir, output_file)
